README.md
=> Fixing link for API reference

.gitignore, samples/Actor/DemoActor/Program.cs, samples/Actor/DemoActor/Properties/launchSettings.json, samples/AspNetCore/ControllerSample/Properties/launchSettings.json, samples/AspNetCore/RoutingSample/Properties/launchSettings.json
Merging release-0.1.0 to master
=> Ading launchsettings.json to use port for local launch

src/Dapr.Client.Grpc/nuspec/Dapr.Client.Grpc.nuspec, src/Dapr.Client/nuspec/Dapr.Client.nuspec
Fixing nuspec for nuget generation.
Fixes https://github.com/dapr/dotnet-sdk/issues/112
=> Fixing nuspec for nuget generation.

docs/get-started-dapr-actor.md
Updated the docs to allow successful walk through of an Actor using .NET Core
No issue to reference, just a docs update
* [NA] Code compiles correctly
* [NA] Created/updated tests
* [/] Extended the documentation
=> Updated docs for .NET Actor

src/Dapr.Actors/Runtime/StateChangeKind.cs
Added a missing period for None option.
=> Added missing period

samples/Actor/ActorClient/Program.cs, samples/AspNetCore/ControllerSample/Program.cs, samples/AspNetCore/RoutingSample/Program.cs, samples/Grpc/GrpcClient/Program.cs, src/Dapr.Actors.AspNetCore/RouterBuilderExtensions.cs, src/Dapr.Actors/Builder/ActorProxyGenerator.cs, src/Dapr.Actors/Client/ActorProxy.cs, src/Dapr.Actors/Client/ActorProxyFactory.cs, src/Dapr.Actors/Client/IActorProxy.cs, src/Dapr.Actors/Client/IActorProxyFactory.cs, src/Dapr.Actors/Communication/ActorMethodDispatcherMap.cs, src/Dapr.Actors/Communication/Client/ActorNonRemotingClient.cs, src/Dapr.Actors/Communication/Client/ActorRemotingClient.cs, src/Dapr.Actors/Communication/IActorRequestMessageBodySerializer.cs, src/Dapr.Actors/Communication/RemoteException.cs, src/Dapr.Actors/IDaprInteractor.cs, src/Dapr.Actors/JsonWriterExtensions.cs, src/Dapr.Actors/Runtime/ActorReminder.cs, src/Dapr.Actors/Runtime/ActorRuntime.cs, src/Dapr.Actors/Runtime/ActorTimer.cs, src/Dapr.Actors/Runtime/DaprStateProvider.cs, src/Dapr.Actors/Runtime/ReminderInfo.cs, test/Shared/TestHttpClient.cs
Removed unused usings throughout solution.
=> Removed unused usings

src/Dapr.Actors/ActorId.cs, test/Dapr.Actors.Test/ActorCodeBuilderTests.cs, test/Dapr.Actors.Test/ActorIdTests.cs, test/Dapr.Actors.Test/ActorMethodInvocationExceptionTests.cs, test/Dapr.Actors.Test/Dapr.Actors.Test.csproj
Random code cleaning for ActorId.cs.
=> Clean ActorId

samples/Grpc/GrpcClient/GrpcClient.csproj, src/Dapr.Client.Grpc/Dapr.Client.Grpc.csproj, test/Dapr.AspNetCore.IntegrationTest/CloudEventsIntegrationTest.cs, test/Dapr.AspNetCore.IntegrationTest/ControllerIntegrationTest.cs, test/Dapr.AspNetCore.IntegrationTest/Dapr.AspNetCore.IntegrationTest.csproj, test/Dapr.AspNetCore.IntegrationTest/RoutingIntegrationTest.cs, test/Dapr.AspNetCore.IntegrationTest/SubscribeEndpointTest.cs, test/Dapr.AspNetCore.Test/CloudEventsMiddlewareTest.cs, test/Dapr.AspNetCore.Test/Dapr.AspNetCore.Test.csproj, test/Dapr.AspNetCore.Test/StateEntryModelBinderTest.cs, test/Dapr.Client.Test/Dapr.Client.Test.csproj, test/Dapr.Client.Test/StateHttpClientTest.cs
Converted current testing from MSTest to xUnit.  Also updated to latest NuGet packages in projects.
Closes #123
=> Moved to xunit for testing

.github/workflows/sdk_build.yml
=> Adding github actions sdk_build.yml

src/Dapr.Actors/JsonReaderExtensions.cs, src/Dapr.Actors/Runtime/ReminderInfo.cs
Change the method return value from TimeSpan? -> TimeSpan
https://github.com/dapr/dotnet-sdk/issues/125
=> Change the method return value from TimeSpan? -> TimeSpan

samples/Actor/ActorClient/Program.cs, samples/Grpc/GrpcClient/Program.cs
=> Making Main async and using Grpc.Net.Client

src/Dapr.AspNetCore/DaprMvcBuilderExtensions.cs
=> Changing AddDapr to return IMvcBuilder

properties/dapr_common.props
Updating the nuget version for 0.2.0 release
=> Updating the nuget version for 0.2.0 release

README.md
Update Readme to correct the RepoRoot
=> Update Readme to correct the RepoRoot

samples/Actor/Readme.md
Changing the application port to 5000
Incorrect port 5001 is mentioned for app port.
=> Changing the application port to 5000

samples/Actor/ActorClient/Program.cs, samples/Actor/DemoActor/DemoActor.cs, src/Dapr.Actors/Runtime/Actor.cs
Removes ToString() methods as they are not needed for string interpolation.
=> Remove unneeded ToString methods

src/Dapr.Actors/JsonWriterExtensions.cs, src/Dapr.Actors/Runtime/ActorTypeInformation.cs
=> Fix format wording

docs/get-started-dapr-actor.md, samples/AspNetCore/ControllerSample/Controllers/SampleController.cs, samples/Grpc/GrpcClient/Readme.md, src/Dapr.Actors.AspNetCore/Dapr.Actors.AspNetCore.csproj, src/Dapr.Actors/Communication/ActorResponseMessageHeader.cs, src/Dapr.Actors/Dapr.Actors.csproj, src/Dapr.Actors/DaprHttpInteractor.cs, src/Dapr.Actors/IDaprInteractor.cs
Capitalize Dapr making consistent throughout comments and with other repo/blog docs.
=> Capitalize Dapr throughout comments

src/Dapr.Actors/Runtime/ActorService.cs, src/Dapr.Actors/Runtime/IActorService.cs
Updated summary types in actors classes
=> Updated summary on classes

docs/get-started-dapr-actor.md, samples/Actor/Readme.md, samples/AspNetCore/RoutingSample/Startup.cs, samples/Grpc/GrpcClient/Readme.md, src/Dapr.Actors/Client/ActorProxy.cs, src/Dapr.Actors/DaprHttpInteractor.cs, src/Dapr.Actors/IDaprInteractor.cs, src/Dapr.Actors/JsonReaderExtensions.cs, src/Dapr.Actors/JsonWriterExtensions.cs, src/Dapr.Actors/Runtime/DaprStateProvider.cs
Updated JSON to uppercase in comments/summaries.
=> Edit JSON to uppercase

samples/Actor/DemoActor/Program.cs
Fixed the spelling mistake on the sample application
* [ X ] Extended the documentation
=> Fix spelling mistake

properties/stylecop/GlobalStylecopSuppressions.cs
Fixed typo in code analysis text message.
=> Fixed typo

src/Dapr.Actors/Client/ActorProxy.cs
=> Remove double word

src/Dapr.Actors/DaprHttpInteractor.cs
=> Fixing Unregistering of timers

properties/dapr_common.props
=> Updating version

samples/AspNetCore/ControllerSample/Readme.md, samples/AspNetCore/RoutingSample/Readme.md
Updating aspnetcore sample docs to include commands for windows
=> Updating aspnetcore sample docs to include commands for windows

.github/workflows/sdk_build.yml, README.md, samples/Actor/ActorClient/ActorClient.csproj, samples/Actor/DemoActor/DemoActor.csproj, samples/Actor/IDemoActor/IDemoActor.csproj, samples/AspNetCore/ControllerSample/ControllerSample.csproj, samples/AspNetCore/RoutingSample/RoutingSample.csproj, samples/Grpc/GrpcClient/GrpcClient.csproj, src/Dapr.Actors.AspNetCore/Dapr.Actors.AspNetCore.csproj, src/Dapr.Actors/Dapr.Actors.csproj, src/Dapr.AspNetCore/Dapr.AspNetCore.csproj, src/Dapr.Client.Grpc/Dapr.Client.Grpc.csproj, src/Dapr.Client/Dapr.Client.csproj, test/Dapr.Actors.Test/Dapr.Actors.Test.csproj, test/Dapr.AspNetCore.IntegrationTest.App/Dapr.AspNetCore.IntegrationTest.App.csproj, test/Dapr.AspNetCore.IntegrationTest/Dapr.AspNetCore.IntegrationTest.csproj, test/Dapr.AspNetCore.Test/Dapr.AspNetCore.Test.csproj, test/Dapr.Client.Test/Dapr.Client.Test.csproj
Fixes https://github.com/dapr/dotnet-sdk/issues/188
=> Build for net core 3.1

src/Dapr.Actors/Runtime/ReminderInfo.cs
Fixes https://github.com/dapr/dotnet-sdk/issues/182
=> Fixing Deserialization of Reminder state

src/Dapr.Client/StateClient.cs, src/Dapr.Client/StateEntry.cs, src/Dapr.Client/StateHttpClient.cs, test/Dapr.AspNetCore.IntegrationTest/StateTestClient.cs, test/Dapr.Client.Test/StateHttpClientTest.cs
Adds support for delete operations to `StateClient` and `StateHttpClient`
Please reference the issue this PR will close: #196
=> Add support for delete operations

samples/Grpc/GrpcClient/Program.cs, src/Dapr.Client.Grpc/Protos/dapr.proto
Dapr runtime has now feature to support multi state stores support. Due to that state APIs are changed. We need to update the proto files in dotnet SDK for GRPC client from dapr repo.
Closes #204 
=> Updating new proto files from dapr repo and fixing the gRPC sample 

samples/Actor/Readme.md
Updated samples/actor/readme.me. Fixed minor issues. Updated to improve readability and based on markdown practices.
=> Improve `samples/Actor/Readme.md`

src/Dapr.Client/AsyncJsonContent.cs, src/Dapr.Client/DaprUris.cs, src/Dapr.Client/PublishClient.cs, src/Dapr.Client/PublishHttpClient.cs, src/Dapr.Client/StateHttpClient.cs, test/Dapr.Client.Test/PublishHttpClientTest.cs
Added a HttpClient implementation of the Dapr publish endpoints following the same pattern as the State and Invoke clients.
This pull request is related to #186 
=> Add PublishHttpClient implementation (#186)

samples/Actor/Readme.md, samples/AspNetCore/ControllerSample/Readme.md, samples/AspNetCore/RoutingSample/Readme.md, src/Dapr.Actors/Constants.cs, src/Dapr.Client/InvokeHttpClient.cs, src/Dapr.Client/PublishHttpClient.cs, src/Dapr.Client/StateHttpClient.cs, test/Dapr.Client.Test/InvokeHttpClientTest.cs, test/Dapr.Client.Test/PublishHttpClientTest.cs, test/Dapr.Client.Test/StateHttpClientTest.cs
This PR changes the address to talk to Dapr from localhost to 127.0.0.1.
=> Using 127.0.0.1 instead of localhost.

samples/Actor/Readme.md
=> Updating readme for Actor Sample to clarify client invocation.

src/Dapr.Actors/DaprError.cs
Please reference the issue this PR will close: #233
=> DaprError deserialization

samples/README.md
Fixed broken link to DaprClient sample
=> Fix broken link to DaprClient sample

src/Dapr.Actors/Runtime/ActorManager.cs
Throw exception if actor method has more than one parameter when invoked through http
#249 
=> Throw exception if actor method has more than one parameter

src/Dapr.Actors.AspNetCore/DaprActorSetupFilter.cs, src/Dapr.Actors.AspNetCore/RouterBuilderExtensions.cs
=> Add health api so that dapr runtime can call it for Actors

src/Dapr.Actors.AspNetCore/RouterBuilderExtensions.cs, src/Dapr.Actors/Runtime/ActorConfig.cs, src/Dapr.Actors/Runtime/ActorRuntime.cs, src/Dapr.Actors/Runtime/ActorSettings.cs, test/Dapr.Actors.Test/Runtime/ActorRuntimeTests.cs
This PR gives the user the option to specify these actor configuration values:
actorIdleTimeout
actorScanInterval
drainOngoingCallTimeout
drainRebalancedActors
Please reference the issue this PR will close: #219
=> Support more actor configuration

samples/AspNetCore/ControllerSample/Readme.md, samples/AspNetCore/ControllerSample/sample.http, samples/AspNetCore/RoutingSample/Readme.md, samples/AspNetCore/RoutingSample/sample.http
Added sample.http files for VS Code [Rest Client Plugin](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) as per the Dapr [Hello World examples](https://github.com/dapr/samples/tree/master/1.hello-world)
=> Add VSCode REST http.sample files

samples/Client/DaprClient/Program.cs, samples/Client/DaprClient/Readme.md
Added new samples in existing project. Samples demonstrate how to invoke GET and POST service operations by using DAPR client API gRPC and events. 
Following new methods added:
>             // This provides an example of how to invoke a method on another REST service that is listening on http.
>             // To use it run RoutingService in this solution.
>             // Invoke deposit operation on RoutingSample service by publishing event.
>             await PublishDepositeEventToRoutingSampleAsync(client);
> 
>             // Invoke deposit operation on RoutingSample service by POST.
>             await InvokeWithdrawServiceOperationAsync(client);
> 
>             // Invoke deposit operation on RoutingSample service by GET.
>             await …
=> Added new samples in existing project.

samples/Client/DaprClient/Readme.md
=> Update to Readme.md

samples/Client/DaprClient/Readme.md
Update readme for api changes.
=> Update readme for api changes

src/Dapr.Actors.AspNetCore/DaprActorSetupFilter.cs, src/Dapr.Actors.AspNetCore/EndpointRouteBuilderExtensions.cs, src/Dapr.Actors.AspNetCore/WebHostBuilderExtensions.cs
Fixes https://github.com/dapr/dotnet-sdk/issues/294
=> Using EndpointRouteBuilder and correcting the order of middleware chaining

src/Dapr.Actors/Runtime/Actor.cs
Actor class should use the ActorTypeName instead of implementation type name for custom actor type name support.
Please reference the issue this PR will close: #310 
=> Fix RegisterReminder, RegisterTimer with correct type name

samples/AspNetCore/ControllerSample/Readme.md, samples/AspNetCore/RoutingSample/Readme.md
dapr publish's -p arg was renamed -d.  
=> cli -p is now -d

samples/AspNetCore/ControllerSample/Readme.md, samples/AspNetCore/RoutingSample/Readme.md
Co-authored-by: LM <lemai>
Cherry pick from master.
cli -p is now -d
=> cli -p is now -d (#325)

docs/get-started-dapr-actor.md
Add generic request type to `InvokeAsync` command.
This PR will close: #332
=> docs: fix InvokeAsync example in get started guide

docs/get-started-dapr-actor.md
Correct RPC actor method names in example.
This PR will close: #334
=> docs: correct actor method names in get started guide

docs/get-started-dapr-actor.md
Improve formatting in code samples in "Getting started with Actors".
=> Improve formatting in "Getting started with Actors"

src/Dapr.Actors/Runtime/Actor.cs
=> Fix typo in Actor docs

samples/Actor/Readme.md, samples/AspNetCore/ControllerSample/Readme.md, samples/AspNetCore/RoutingSample/Readme.md
Fixes# https://github.com/dapr/dotnet-sdk/issues/316
Adding suggestion from https://github.com/dapr/dotnet-sdk/issues/316
=> Adding a note about running service with IIS express in Readme.md for samples.

src/Dapr.Actors/DaprHttpInteractor.cs, src/Dapr.Actors/IDaprInteractor.cs, test/Dapr.Actors.Test/DaprHttpInteractorTest.cs
Adding unit tests for DaprHttpInteractor in Actors, removing unused code for DaprHttpInteractor
Fixes https://github.com/dapr/dotnet-sdk/issues/365
=> Adding unit tests for DaprHttpInteractor in Actors, removing unused code.

docs/get-started-dapr-actor.md, samples/Actor/Readme.md
Fixes #https://github.com/dapr/dotnet-sdk/issues/363
=> update docs for arg changes in cli

.github/workflows/sdk_build.yml
=> Test change for nuget push

src/Dapr.AspNetCore/DaprMvcBuilderExtensions.cs, src/Dapr.AspNetCore/DaprServiceCollectionExtensions.cs, test/Dapr.AspNetCore.Test/DaprMvcBuilderExtensionsTest.cs, test/Dapr.AspNetCore.Test/DaprServiceCollectionExtensions.cs, test/Dapr.AspNetCore.Test/DaprServiceCollectionExtensionsTest.cs
Changed the checks on the existence of the marker-service during DI registration of Dapr services. 
See referenced issue #390 for the problems that this PR fixes.
Issue #390 
=> Fix use of marker services in DI registration

samples/Client/DaprClient/Program.cs, samples/Client/DaprClient/Readme.md
Cleaning up the sample
#405 
Please reference the issue this PR will close: #405 
=> cleanup sample

.github/workflows/sdk_build.yml
=> Fix github-release version

.github/workflows/sdk_build.yml
Merge back release-0.11 branch into master
=> Fix github-release-cli version (#407)

README.md, global.json, samples/Directory.Build.props, src/Dapr.Actors.AspNetCore/Dapr.Actors.AspNetCore.csproj, src/Dapr.Actors/Dapr.Actors.csproj, src/Dapr.AspNetCore/Dapr.AspNetCore.csproj, src/Directory.Build.props, test/Directory.Build.props
- Remove documentation files (and warnings) for samples and tests
- Remove redundant XML for resource files (this is the default behavior now)
- Specify required minimum SDK version
- Update readme to add mac/linux and reflect newer practices
=> Improvements and cleanups to projects and readme

samples/AspNetCore/ControllerSample/Controllers/SampleController.cs, samples/Client/DaprClient/DaprClient.csproj, samples/Client/DaprClient/Program.cs, samples/Client/DaprClient/Readme.md
Modified the sample to demonstrate how to extract error messages from RpcException
#399 
Please reference the issue this PR will close: #399 
=> grpc exception handling sample

samples/AspNetCore/ControllerSample/Controllers/SampleController.cs, samples/Client/DaprClient/DaprClient.csproj, samples/Client/DaprClient/Program.cs, samples/Client/DaprClient/Readme.md, src/Dapr.Client/Dapr.Client.csproj, test/Dapr.Client.Test/Dapr.Client.Test.csproj
=> Cherry pick grpc exception handling change to 0.11

.github/scripts/get_release_version.py
Remove set-env due to CVE-2020-15228
Please reference the issue this PR will close: https://github.com/dapr/dotnet-sdk/issues/417
=> Remove set-env due to CVE-2020-15228

src/Dapr.Actors/ActorId.cs
Use GUID to generate random actor id
#415 
Please reference the issue this PR will close: #415 
=> use Guid to generate unique Actor id

src/Dapr.Actors.AspNetCore/EndpointRouteBuilderExtensions.cs, src/Dapr.Actors.AspNetCore/WebHostBuilderExtensions.cs, src/Dapr.Actors/Runtime/ActorRuntime.cs, test/Dapr.Actors.Test/Runtime/ActorRuntimeTests.cs
This change removes a mutable static instance - this is low-hanging
fruit design improvement and helps us make these features more flexible
in the future.
Contributes to: #416
=> Remove static instance of ActorRuntime

.codecov.yml, .github/workflows/sdk_build.yml, README.md, test/Dapr.Actors.Test/Dapr.Actors.Test.csproj, test/Dapr.AspNetCore.IntegrationTest/Dapr.AspNetCore.IntegrationTest.csproj, test/Dapr.AspNetCore.Test/Dapr.AspNetCore.Test.csproj, test/Dapr.Client.Test/Dapr.Client.Test.csproj
Add codecov integration
Please reference the issue this PR will close: #436
=> Added codecov integration (#436)

src/Dapr.Actors/Runtime/Actor.cs
#406 
Please reference the issue this PR will close: #406 
=> naming convention

src/Dapr.Actors/Runtime/ActorTypeInformation.cs
Made ActorTypeInformation constructor private
#461 
Please reference the issue this PR will close: #461 
RELEASE NOTE: removed public constructor on ActorTypeInfo - this is a breaking change but unlikely to impact users as it was not useful before
=> removed ActorTypeInformation public constructor

samples/Client/DaprClient/Readme.md
=> Fix documentation [#481]

src/Dapr.AspNetCore/StateEntryApplicationModelProvider.cs
Added a check for the existence of Binding Info on action parameters
#496 
Please reference the issue this PR will close: #496
=> #496 - add a check if there is no BindingInfo for action parameters

properties/dapr_managed_netcore.props
Change the pre-release tag from preview to rc to align with the runtime version
#482 
Please reference the issue this PR will close: #482 
=> Change package versioning from preview to rc

src/Dapr.Client/Protos/dapr/proto/dapr/v1/appcallback.proto, src/Dapr.Client/Protos/dapr/proto/dapr/v1/dapr.proto
=> update proto files

samples/Actor/ActorClient/Program.cs, samples/AspNetCore/ControllerSample/Readme.md, samples/AspNetCore/RoutingSample/Readme.md, samples/AspNetCore/SecretStoreConfigurationProviderSample/components/secretstore.yaml
Minor fixes in samples as per the latest runtime/CLI changes
Please reference the issue this PR will close: #508 
=> Samples fixes

docs/get-started-dapr-actor.md
#514 
Please reference the issue this PR will close: #514 
=> Fix issues in docs

docs/get-started-dapr-actor.md
Update docs to document some 0.12 changes that were missed
Fixes: #499
=> Update actor docs for 0.12 changes

docs/get-started-dapr-actor.md, samples/Actor/ActorClient/Program.cs, samples/AspNetCore/ControllerSample/Readme.md, samples/AspNetCore/RoutingSample/Readme.md, samples/AspNetCore/SecretStoreConfigurationProviderSample/components/secretstore.yaml, src/Dapr.Client/Protos/dapr/proto/dapr/v1/appcallback.proto, src/Dapr.Client/Protos/dapr/proto/dapr/v1/dapr.proto
Merge release-1.0.0 into master after 1.0.0-rc02 release
=> Merge release-1.0.0 into master

src/Dapr.Actors.AspNetCore/Runtime/DependencyInjectionActorActivator.cs, src/Dapr.Actors/Runtime/ActorActivator.cs, src/Dapr.Actors/Runtime/ActorManager.cs, src/Dapr.Actors/Runtime/DefaultActorActivator.cs, src/Dapr.Client/DaprClient.cs, src/Dapr.Client/DaprClientGrpc.cs, src/Dapr.Client/StateEntry.cs, test/Dapr.Actors.Test/Runtime/ActorManagerTests.cs, test/Dapr.Actors.Test/Runtime/ActorRuntimeTests.cs, test/Dapr.AspNetCore.IntegrationTest/StateTestClient.cs
We should replace the use of ValueTask in the DaprClient with Task.
Please reference the issue this PR will close: #517 
=> Replace ValueTask with Task

docs/troubleshooting-pub-sub.md
Adds a troubleshooting doc page for pub/sub
No issue, we've gotten a few different support requests with pub/sub, so I wanted to write a step-by-step guide.
=> Add troubleshooting guide for pub/sub

src/Dapr.Client/Protos/dapr/proto/dapr/v1/dapr.proto
Update protobuf files from dapr/dapr
=> Update protobuf files

samples/Client/DaprClient/InvokeServiceGrpcExample.cs, src/Dapr.Actors/Runtime/Actor.cs, src/Dapr.Actors/Runtime/ActorHost.cs, src/Dapr.Actors/Runtime/ActorManager.cs, src/Dapr.Actors/Runtime/ActorStateManager.cs, src/Dapr.Client/DaprClientGrpc.cs, src/Dapr.Client/Protos/dapr/proto/dapr/v1/dapr.proto, test/Dapr.Actors.AspNetCore.Test/Runtime/DependencyInjectionActorActivatorTests.cs, test/Dapr.Actors.Test/ApiTokenTests.cs, test/Dapr.Actors.Test/DaprHttpInteractorTest.cs, test/Dapr.Actors.Test/Runtime/ActorRuntimeOptionsTests.cs, test/Dapr.Actors.Test/Runtime/ActorTests.cs, test/Dapr.Actors.Test/Runtime/DefaultActorActivatorTests.cs, test/Dapr.Client.Test/PublishEventApiTest.cs
Merge release-1.0.0 into master after rc5
=> Merge release-1.0.0 into master after rc5

src/Dapr.AspNetCore/CloudEventsMiddleware.cs, src/Dapr.Client/Protos/dapr/proto/common/v1/common.proto, src/Dapr.Client/Protos/dapr/proto/dapr/v1/appcallback.proto, src/Dapr.Client/Protos/dapr/proto/dapr/v1/dapr.proto, test/Dapr.AspNetCore.Test/CloudEventsMiddlewareTest.cs
Read data_base64 field
#582 
Please reference the issue this PR will close: #582 
=> read binary data

src/Dapr.Client/DaprClient.cs
Adds missing default value for cancellation token.
This PR will close: #577 
=> Add missing cancellation token

examples/README.md
=> Fix broken link

daprdocs/content/en/dotnet-sdk-docs/dotnet-troubleshooting/dotnet-troubleshooting-pubsub.md
Found this was missing with a user's help
=> Add one more case to troubleshooting guide

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/_index.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-client.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-howto.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-usage.md
This change runs through the getting started docs and improves trims all
of the unnecessary fat. I've reorganized all of the details that aren't
relevant as part of the first tutorial into separate docs.
I've also fleshed out all of the content we have to be relevant to a new
user and added new sections like DI and logging.
Fixes: #546
Fixes: #612
=> Improve actor getting started and add more docs

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-howto.md
Fixed links in docs due to renamed files.
=> Fix docs links

daprdocs/content/en/dotnet-sdk-docs/_index.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/_index.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-client.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-howto.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-usage.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-development/_index.md
Fix a couple small inconsistencies and non-unique titles
=> Update actors docs

daprdocs/content/en/dotnet-sdk-docs/dotnet-troubleshooting/dotnet-troubleshooting-pubsub.md
Thanks to @JadynWong to report
=> Fix error description in dotnet-troubleshooting-pubsub.md

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-usage.md
Use the correct method call of "AddActors()" when registering Actors.
Please reference the issue this PR will close: https://github.com/dapr/docs/issues/1465
* [] Code compiles correctly
* [] Created/updated tests
=> Use correct method call (AddActors) for registering Actors.

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-client.md
Fix typo in .NET Actor client docs
N/A
=> Fix typo in .NET Actor client docs

examples/AspNetCore/ControllerSample/Controllers/SampleController.cs, examples/AspNetCore/ControllerSample/CustomTopicAttribute.cs, examples/AspNetCore/ControllerSample/Properties/launchSettings.json, src/Dapr.AspNetCore/DaprEndpointConventionBuilderExtensions.cs, src/Dapr.AspNetCore/DaprEndpointRouteBuilderExtensions.cs, src/Dapr.AspNetCore/ITopicMetadata.cs, src/Dapr.AspNetCore/TopicAttribute.cs, test/Dapr.AspNetCore.IntegrationTest.App/CustomTopicAttribute.cs, test/Dapr.AspNetCore.IntegrationTest.App/DaprController.cs, test/Dapr.AspNetCore.IntegrationTest/SubscribeEndpointTest.cs
Adds support for providing pubsub and topic names during runtime.
Please reference the issue this PR will close: #678 
=> Adds support for providing pubsub and topic names during runtime.

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-client.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-usage.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-development/dotnet-development-docker-compose.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-development/dotnet-development-tye.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-troubleshooting/dotnet-troubleshooting-pubsub.md
=> Fix typo in .NET SDK docs

src/Dapr.Actors/Runtime/ActorRuntime.cs, src/Dapr.Actors/Runtime/ActorRuntimeOptions.cs, test/Dapr.Actors.Test/Runtime/ActorRuntimeOptionsTests.cs, test/Dapr.Actors.Test/Runtime/ActorRuntimeTests.cs
Adds support for configuring the actor reminder storage partitions
https://github.com/dapr/dapr/issues/2889
=> Configurable actor reminder storage partitions

examples/AspNetCore/GrpcServiceSample/Services/BankingService.cs
=> Return TopicEventResponse instead of null

src/Dapr.Client/Protos/dapr/proto/common/v1/common.proto, src/Dapr.Client/Protos/dapr/proto/dapr/v1/appcallback.proto, src/Dapr.Client/Protos/dapr/proto/dapr/v1/dapr.proto
This commit includes the copied files from dapr/dapr. These are used
to generate the gRPC client. Included in the update are:
- Configuration API
- Query API
Partial for:
- #777 
- #787 
=> Update Dapr Protos

daprdocs/content/en/dotnet-sdk-docs/dotnet-client/_index.md
Add documentation for GetConfiguration API
This is for: [Docs Issue](https://github.com/dapr/docs/issues/2094)
=> Add documentation for GetConfiguration API

daprdocs/content/en/dotnet-sdk-docs/dotnet-client/_index.md
This commit adds a client example for the Query API. It also
marks the Configuration API as alpha.
Please reference the issue this PR will close: #820 
=> Add client example for Query API (Alpha)

.github/workflows/itests.yml, .github/workflows/sdk_build.yml, test/Dapr.Actors.AspNetCore.IntegrationTest.App/Dapr.Actors.AspNetCore.IntegrationTest.App.csproj, test/Dapr.Actors.AspNetCore.IntegrationTest/Dapr.Actors.AspNetCore.IntegrationTest.csproj, test/Dapr.Actors.AspNetCore.Test/Dapr.Actors.AspNetCore.Test.csproj, test/Dapr.Actors.Test/Dapr.Actors.Test.csproj, test/Dapr.AspNetCore.IntegrationTest.App/Dapr.AspNetCore.IntegrationTest.App.csproj, test/Dapr.AspNetCore.IntegrationTest/Dapr.AspNetCore.IntegrationTest.csproj, test/Dapr.AspNetCore.Test/Dapr.AspNetCore.Test.csproj, test/Dapr.Client.Test/Dapr.Client.Test.csproj, test/Dapr.E2E.Test.Actors/Dapr.E2E.Test.Actors.csproj, test/Dapr.E2E.Test.App.Grpc/Dapr.E2E.Test.App.Grpc.csproj, test/Dapr.E2E.Test.App.ReentrantActor/Dapr.E2E.Test.App.ReentrantActors.csproj, test/Dapr.E2E.Test.App/Dapr.E2E.Test.App.csproj, test/Dapr.E2E.Test/Dapr.E2E.Test.csproj, test/Dapr.Extensions.Configuration.Test/Dapr.Extensions.Configuration.Test.csproj
Add .NET 6 build targets for tests
Please reference the issue this PR will close: #794 
=> Add .NET 6 build targets for tests

.github/workflows/sdk_build.yml
Update Parse Trx github action.
The action is failing on master with a parsing error that appears to be fixed in a later version of the action.
=> Update Parse Trx github action

daprdocs/content/en/dotnet-sdk-docs/dotnet-development/_index.md
Signed-off-by: Hannah Hunter <hannahhunter@microsoft.com>
Fixed typo; small grammar fixes (punctuation)
This PR will close: [#2254](https://github.com/dapr/docs/issues/2254)
=> typo fixes to documentation

.github/workflows/itests.yml
Upgrade dapr/cli used in e2e test workflow
Please reference the issue this PR will close: Chore
=> Upgrade dapr/cli used in e2e test workflow

.github/workflows/fossa.yml, README.md
Add Fossa scan to the CI workflow
https://github.com/dapr/dotnet-sdk/issues/843
Please reference the issue this PR will close: #843 
=> Add Fossa scan to the CI workflow

.github/workflows/itests.yml
Update Dapr and CLI to 1.8 RCs
Please reference the issue this PR will close: Endgame
=> Update Dapr and CLI to 1.8

src/Dapr.Actors.AspNetCore/ActorsEndpointRouteBuilderExtensions.cs, src/Dapr.Actors/DaprHttpInteractor.cs, test/Dapr.Actors.Test/ActorMethodInvocationExceptionTests.cs, test/Dapr.E2E.Test.Actors/ExceptionTesting/IExceptionActor.cs, test/Dapr.E2E.Test.App/Actors/ExceptionActor.cs, test/Dapr.E2E.Test.App/Startup.cs, test/Dapr.E2E.Test/Actors/E2ETests.ExceptionTests.cs
Signed-off-by: Amulya Varote <amulyavarote@microsoft.com>
Added a method that gives line number and the method name for the actor invocation.
Please reference the issue this PR will close: #904 
=> Added exception details to the actor invocation

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-client.md
Signed-off-by: Amulya Varote <amulyavarote@microsoft.com>
Added Actor method invocation exception details.
Please reference the issue this PR will close: #NA
=> Added actor method exception details docs

src/Dapr.Client/DaprClient.cs, src/Dapr.Client/DaprClientGrpc.cs
Report the SDK's name and version in the User-Agent header. See: dapr/dapr#5309
=> Report standardized user-agent with SDK version

README.md
Signed-off-by: Amulya Varote <amulyavarote@microsoft.com>
Changed broken link in README
Please reference the issue this PR will close: #969 
=> Changed broken link in README

examples/Workflow/README.md, examples/Workflow/WorkflowConsoleApp/Activities/RequestApprovalActivity.cs, examples/Workflow/WorkflowConsoleApp/Models.cs, examples/Workflow/WorkflowConsoleApp/Program.cs, examples/Workflow/WorkflowConsoleApp/Workflows/OrderProcessingWorkflow.cs, src/Dapr.Client/DaprClient.cs, src/Dapr.Workflow/WorkflowContext.cs
This PR makes two main changes:
1. Updates the workflow console app example with external event handling (order approval)
2. Updates some of the XML documentation for the workflow APIs with more information about exception handling
The latter change was a result of manually testing the updated example. It will help developers know what types of exceptions to expect.
I also corrected some outdated information in the workflow's README.md file.
Part of https://github.com/dapr/dotnet-sdk/issues/1079 (covers just the "raise event" work-item)
FYI @halspang @RyanLettieri @nyemade-uversky
=> [Workflow] Add human approval to the workflow example

examples/Workflow/WorkflowConsoleApp/demo.http
Update the HTTP requests to incorporate the latest changes made to the workflow management APIs.
=> Fix HTTP examples in Workflow Console App

examples/Workflow/README.md
The original link is NOT FOUND.
=> Modify broken links in README

.github/holopin.yml
Updated .github/holopin.yml. 
Please reference the issue this PR will close: #1270
=> Updated .github/holopin.yml. Fixes #1270

README.md
Updated badges in the project readme as asked in #1283 
#1283 
=> Standardize README with shield badges

daprdocs/content/en/dotnet-sdk-docs/dotnet-workflow/dotnet-workflow-howto.md
update .NET SDK docs for workflow from beta to stable
Please reference the issue this PR will close: dapr/docs#3870
=> [docs] Update Workflow to stable

daprdocs/content/en/dotnet-sdk-docs/dotnet-code-analysis/_index.md, src/Dapr.Actors.Analyzers/Dapr.Actors.Analyzers/ActorRegistrationAnalyzer.cs, src/Dapr.Actors.Analyzers/Dapr.Actors.Analyzers/AnalyzerReleases.Shipped.md, src/Dapr.Actors.Analyzers/Dapr.Actors.Analyzers/MappedActorHandlersAnalyzer.cs, src/Dapr.Actors.Analyzers/Dapr.Actors.Analyzers/PreferActorJsonSerializationAnalyzer.cs, src/Dapr.Actors.Analyzers/Dapr.Actors.Analyzers/Resources.Designer.cs, src/Dapr.Actors.Analyzers/Dapr.Actors.Analyzers/Resources.resx, src/Dapr.Actors.Analyzers/Dapr.Actors.Analyzers/TimerCallbackMethodPresentAnalyzer.cs, src/Dapr.Jobs.Analyzer/AnalyzerReleases.Shipped.md, src/Dapr.Jobs.Analyzer/MapDaprScheduledJobHandlerAnalyzer.cs, src/Dapr.Jobs.Analyzer/Resources.Designer.cs, src/Dapr.Jobs.Analyzer/Resources.resx
This adds documentation to reflect the various analyzers being added to the release and providing a centralized place to consolidate diagnostic IDs. As such, this PR not only adds a page to the docs, but also does a pass through existing analyzers to assign updated diagnostic IDs to each.
=> Adding Analyzer documentation, consolidating diagnostic IDs

Directory.Packages.props
=> Durable task package update

Directory.Packages.props
Version bump for durabletask package to included updated protos
=> DurableTask protos update - version bump

Directory.Packages.props
Building against latest durabletask package
=> Dapr.DurableTask package update

.github/workflows/sdk_build.yml
=> Reverting publish to fire as it did - will fix in 1.17

.github/workflows/sdk_build.yml
=> Added 'build' and 'test' back to the publish dependencies

.github/workflows/itests.yml
Updated to use 1.16.0-rc4 in the integration tests.
=> Updated integration test to 1.16.0-rc.4

daprdocs/content/en/dotnet-sdk-docs/dotnet-client/_index.md, src/Dapr.Client/DaprClientGrpc.cs
Updated documentation for Dapr.Client to generally use the DI-approach to instantiating a client in lieu of the static builder as that's being increasingly phased out.
=> DaprClient DI docs update

all.sln, daprdocs/content/en/dotnet-sdk-docs/dotnet-ai/dotnet-ai-extensions-howto.md, examples/AI/MicrosoftAiExtensionsDemo/MicrosoftAiExtensionsDemo.csproj, examples/AI/MicrosoftAiExtensionsDemo/Program.cs, src/Dapr.AI.Microsoft.Extensions/Dapr.AI.Microsoft.Extensions.csproj, src/Dapr.AI.Microsoft.Extensions/DaprChatClient.cs, src/Dapr.AI.Microsoft.Extensions/DaprChatClientExtensions.cs, src/Dapr.AI.Microsoft.Extensions/DaprChatClientOptions.cs
- Renamed package/example
- Fixed a tooling deserialization issue associated with the JSON string potentially included in the tool arguments
- Added documentation detailing how to use this new capability
This work is associated with the already merged work in #1620 
=> Renaming Dapr.AI.DotnetExtensions to Dapr.AI.Microsoft.Extensions

Directory.Packages.props
Updated Dapr.DurableTask.* packages to 1.16.5 to incorporate changes to logging suppression defaults.
=> Updated durable task version

Directory.Packages.props
Updated Dapr.DurableTask package version to 1.16.6
=> Updated DurableTask package version
