dapr/dotnet-sdk

src/Dapr.Actors/Runtime/ActorManager.cs
Use Array.Empty<byte>() for empty byte arrays instead of allocating an empty array.
https://github.com/dapr/dotnet-sdk/issues/119
=> changing byte[0] to Arry.Empty<byte>()

README.md, samples/Actor/Readme.md
Fix sampels readme and repo readme to refer to code.sln.
Closes #130
=> Fix samples readme and repo readme to refer to code.sln.

samples/Actor/ActorClient/Program.cs, samples/Actor/DemoActor/DemoActor.cs, samples/Actor/IDemoActor/IDemoActor.cs
Updating sample which shows more calls with remoting for methods which throw exception & call to method with no return and arg.
This also covers the calls for methods with no return type as pointed in this issue: https://github.com/dapr/dotnet-sdk/issues/129
=> Updating sample which shows more calls with remoting.

src/Dapr.Actors/JsonReaderExtensions.cs, test/Dapr.Actors.Test/JsonReaderExtensionTests.cs
Replaced string.Substring usage with Span API.
https://github.com/dapr/dotnet-sdk/issues/134
=> Move to using span slicing instead of string substrings

properties/dapr_managed_stylecop.props
Fixes: #155
This will prevent Stylecop.Analyzers from being pulled in as a
dependency transitively.
Please reference the issue this PR will close: #155
Verified the generated nuspec:
**Before**
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
<metadata>
<id>Dapr.Client</id>
<version>0.2.0-preview01</version>
<authors>dapr.io</authors>
<owners>dapr.io</owners>
<requireLicenseAcceptance>true</requireLicenseAcceptance>
<license type="expression">MIT</license> …
```
=> Make Stylecop.Analyzers a private dependency

samples/Actor/DemoActor/Properties/launchSettings.json, samples/Actor/Readme.md
Changing the application port to 5000 in launch settings
This change will always run the application on port 5000 be in development or production environment.
=> Changing the application port to 5000 in launch settings

properties/dapr_common.props, properties/dapr_managed_stylecop.props
cherry-pick fedfd4a (PR #156) to release new nuget package for 0.2.0
=> Making stylecopanalyzers private dependency and updating version

test/Dapr.AspNetCore.IntegrationTest/AppWebApplicationFactory.cs
Removes console spew when running the integration tests at the command
line
Fixes: #193
Disables logging for the test host created by integration tests. 
Please reference the issue this PR will close: #193
=> Get the integration tests to calm down

src/Dapr.Client/StateHttpClient.cs, test/Dapr.Client.Test/StateHttpClientTest.cs
We were missing tests for the case where the HttpClient has a
BaseAddress set. In these case we'd generate an incorrect URL.
Fixes: #192
Fixed #192 (add missing slash) and added unit tests
Please reference the issue this PR will close: #192
=> Fix URL generation when BaseAddress is used

src/Dapr.Actors/Runtime/ActorService.cs, src/Dapr.Actors/Runtime/DaprStateProvider.cs, src/Dapr.Actors/Runtime/DataContractStateSerializer.cs, src/Dapr.Actors/Runtime/IActorStateSerializer.cs
Summary of changes:
- Serializing Actor state as json
- Moving older DataContract serializer into its own class so that it can exposed later as a Service Fabric compatibility mode
- Adding an interface for serialization/deserialization so that it can be exposed to users.
Fixes https://github.com/dapr/dotnet-sdk/issues/58
=> Serializing actor state as json by default.

src/Dapr.Client/InvokeHttpClient.cs, test/Dapr.Client.Test/InvokeHttpClientTest.cs
InvokeMethodAsync<TRequest,TResponse> is not considering json serialization. Is not possible to serialize C# PascalCase properties to Camelse
#234 
* [X ] Code compiles correctly
=> Pass serializer options to InvokeMethodAsync<TRequest,TResponse> #234

src/Dapr.Actors.AspNetCore/Dapr.Actors.AspNetCore.csproj
Adding ref. to System.IO.Pipelines explicitly to work around build issue with .netcore sdk 3.1.102
https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#net-core-312
This will be reverted when the fix will be available in future .net core sdk.
=> Adding ref. to System.IO.Pipelines explicitly to work around build issue with .netcore sdk 3.1.102

src/Dapr.Client/DaprClientBuilder.cs
Fixes #257 
Changing default dapr grpc port to 50001
https://github.com/dapr/dapr/blob/d8aa4008346735aa8e4746626c0a7a5eb4e9a9fa/pkg/runtime/config.go#L24
=> changing default dapr grpc port

src/Dapr.Client/DaprClientBuilder.cs
Allows the DaprClient to work with mTLS enabled grpc endpoint when https endpoint is provided with DaprClientBuilder.UseEndpoint
It will be cherry-picked into 0.5.0 branch to realse a new nuget package.
The change will be reverted from master branch for 0.6.0 when the issue is fixed in Dapr runtime.
Fixes https://github.com/dapr/dotnet-sdk/issues/261
=> Workaround for mTLS enabled Dapr endpoint.

src/Dapr.Client/DaprClientBuilder.cs
Summary of changes:
- This reverts the workaroung which was added to handle mtls on dapr endpoints. With 0.6.0 release, there will be a separate endpoint for app->dapr  which will not use tls. This was the original issue: https://github.com/dapr/dotnet-sdk/issues/261
- Also exposes option to provide GrpcChannelOptions to allow more customizations by users
=> Revert the workaround added to work with mTLS enabled grpc endpoint.

src/Dapr.Actors/ActorId.cs, test/Dapr.Actors.Test/ActorIdTests.cs
Fixes https://github.com/dapr/dotnet-sdk/issues/277
Add an empty string check in the ActorId constructor.
The tests have been modified by adding :
1) When Id is an empty string test => Check Exception
2) When Id is white spaces test => Check OK
Please reference the issue this PR will close: #_277_
=> Initializing ActorId with an empty string should throw an exception

src/Dapr.Client/DaprClient.cs, src/Dapr.Client/DaprClientGrpc.cs, test/Dapr.Client.Test/PublishEventApiTest.cs
pub/sub - rename refs to 'content' to 'data'
https://github.com/dapr/dapr/issues/1370
=> pub/sub - rename refs to 'content' to 'data'

docs/get-started-dapr-actor.md
- Explicitly specify netcoreapp3.1 on project creation
- Remove documentation section on updating to netcoreapp3.0 which is obsolte
- Fix missing using statements in MyActoreService code updates
=> Update documentation to specify framework version on creation

docs/get-started-dapr-actor.md
`serialziable` -> `serializable` in `docs/get-started-dapr-actor.md`.
This PR will close: #330
=> docs: correct typo in get started guide

.github/workflows/sdk_build.yml, properties/dapr_nuget.props, src/Dapr.Actors.AspNetCore/Dapr.Actors.AspNetCore.csproj, src/Dapr.AspNetCore/Dapr.AspNetCore.csproj, src/Directory.Build.props
Fixes #251 #339 #340
Updated dotnet sdk
Generate .snupkg
Upload packages for tags to nuget.org
Enable sourcelink
Enable Deterministic build for github actions
=> Updated dotnet sdk in github actions

src/Dapr.Client/Dapr.Client.csproj, src/Dapr.Client/Protos/dapr/proto/dapr/v1/appcallback.proto, test/Dapr.Client.Test/Dapr.Client.Test.csproj, test/Dapr.Client.Test/InvokeApiTest.cs, test/Shared/AppCallbackClient.cs, test/Shared/ProtobufUtils.cs
To implement service invocation for a gRPC API, a user must implement the AppCallback service on the callee site. Currently this must be done by integrating the `appcallpack.proto` file as also the depending `common.proto` file into the gRPC service application. The `Dapr.Client` package contains already the same `common.proto` file to generate the client classes. This results in a CS0433 error, because the `Dapr.Client` package and the generated AppCallback service will contain a `Dapr.Client.Autogen.Grpc.v1` namespace with the exact same classes.
This pull requests integrates the `appcallpack.proto` into the client package. With this fix the user does not need to integrate the proto files by itself.
See: https://gitter.im/Dapr/community?at=5f14b7e98a9a0a08cbab5d53
Please make sure …
=> Include the appcallback.proto into the Dapr.Client package

.github/workflows/sdk_build.yml, properties/dapr_common.props, properties/dapr_managed_netcore.props, properties/dapr_nuget.props
Summary of changes:
- With these changes, no need to update versions manually, they will be determined using the git tags
- Version for assembly and nuget package is derived form tag which are created at release time. MinVer is used for it
=> Determine assembly, nuget versions based on git tags.

src/Dapr.AspNetCore/StateEntryModelBinderProvider.cs, test/Dapr.AspNetCore.IntegrationTest.App/DaprController.cs, test/Dapr.AspNetCore.IntegrationTest/ControllerIntegrationTest.cs
Even when there's no Dapr attribute used on an Action, all model binders are checked by ASP.NET from the top against a parameter when needed. StateEntryModelBinderProvider does not handle a null reference when called in this context. This PR fixes that.
#368 
=> Fixing null reference exception when no model binder provided

src/Dapr.Client/Dapr.Client.csproj, test/Dapr.Client.Test/Dapr.Client.Test.csproj
Upgrade grpc nuget pkg to 2.32.0. Now, it populates grpc-status-details-bin to handle grpc rich error. Next PR will show how to extract errorinfo from the metadata.
Code example:
```
try {
await InvokeWithdrawServiceOperationAsync(client);
} catch (Grpc.Core.RpcException ex) {
System.Console.WriteLine(Encoding.UTF8.GetString(ex.Trailers.GetValueBytes("grpc-status-details-bin")));
}
```
Output:
```
== APP ==       Not Foundx
== APP == (type.googleapis.com/google.rpc.ErrorInfoL
== APP ==       Not Founddapr.io
== APP ==       http.code404$
== APP == http.error_messagenot found data
```
https://github.com/dapr/dotnet-sdk/issues/399
=> Upgrade grpc to 2.32.0

src/Dapr.Actors.AspNetCore/Dapr.Actors.AspNetCore.csproj, src/Dapr.AspNetCore/Dapr.AspNetCore.csproj
This is a workaround for https://github.com/dotnet/sdk/issues/14019
which prevents the current prerelease dotnet SDK
`5.0.100-rc.1.20452.10` from successfully building the repo.
Users attempting to build with the bugged release will see a compiler
error related to the `System.IO.Pipelines` assembly.
The explicit reference to `System.IO.Pipelines` is harmless long term,
but can be removed when the underlying bug is fixed and shipped in a GA
release (likely 5.0.100 GA).
Underlying issue is a dotnet SDK bug  - https://github.com/dotnet/sdk/issues/14019
We should make sure that the repo is buildable by wide audience of contributors 😉 
=> Workaround .NET SDK bug with pipelines package

.gitignore
Makes sure we exclude the generated `coverage.json` files from git. We
don't want these to get accidentally committed if someone is running
coverage on their own machine.
Follow up from #443 
=> Add coverlet output to gitignore

src/Dapr.Client/Protos/dapr/proto/dapr/v1/appcallback.proto, src/Dapr.Client/Protos/dapr/proto/dapr/v1/dapr.proto
Copied over proto files from dapr repo
=> update proto files for rc release

.github/workflows/sdk_build.yml, README.md, azure-pipelines.yml, global.json, properties/dapr_managed_netcore.props, test/Dapr.Actors.AspNetCore.IntegrationTest.App/Dapr.Actors.AspNetCore.IntegrationTest.App.csproj, test/Dapr.Actors.AspNetCore.IntegrationTest/Dapr.Actors.AspNetCore.IntegrationTest.csproj, test/Dapr.Actors.AspNetCore.Test/Dapr.Actors.AspNetCore.Test.csproj, test/Dapr.Actors.Test/Dapr.Actors.Test.csproj, test/Dapr.AspNetCore.IntegrationTest.App/Dapr.AspNetCore.IntegrationTest.App.csproj, test/Dapr.AspNetCore.IntegrationTest/Dapr.AspNetCore.IntegrationTest.csproj, test/Dapr.AspNetCore.Test/Dapr.AspNetCore.Test.csproj, test/Dapr.Client.Test/Dapr.Client.Test.csproj, test/Dapr.Extensions.Configuration.Test/Dapr.Extensions.Configuration.Test.csproj
Update the repo to run tests against .NET 5. There's no change in the support matrix or how the dotnet-sdk libraries build - the difference is that both 3.1 and 5.0 are tested now.
We'll require the .NET 5 SDK for contributing the repo from now on. 
Please reference the issue this PR will close: #429
=> Add .NET 5 testing

src/Dapr.Actors/Runtime/ActorStateManager.cs, src/Dapr.Actors/Runtime/IActorStateManager.cs
This API was intended to query the state store for all existing state
entries for the actor. However support for this in the dapr runtime has
not be implemented. We're removing this API to avoid confusion since
it does not behave as expected. We can revisit this in the future based
on feedback.
Fixes: #53
=> Remove GetAllStateNamesAsync

docs/cancellation-tokens.md, samples/Client/DaprClient/DaprClient.csproj, samples/Client/DaprClient/Example.cs, samples/Client/DaprClient/InvokeServiceGrpcExample.cs, samples/Client/DaprClient/InvokeServiceHttpClientExample.cs, samples/Client/DaprClient/InvokeServiceHttpExample.cs, samples/Client/DaprClient/Program.cs, samples/Client/DaprClient/PublishEventExample.cs, samples/Client/DaprClient/Readme.md, samples/Client/DaprClient/StateStoreETagsExample.cs, samples/Client/DaprClient/StateStoreExample.cs, samples/Client/DaprClient/StateStoreTransactionsExample.cs, src/Dapr.Client/BulkStateItem.cs, src/Dapr.Client/DaprClient.cs, src/Dapr.Client/InvocationHandler.cs, src/Dapr.Client/StateTransactionRequest.cs, test/Dapr.AspNetCore.IntegrationTest/StateTestClient.cs, test/Dapr.Client.Test/DaprClientTest.cs, test/Dapr.Client.Test/InvocationHandlerTests.cs
- Adds a new message handler for HttpClient interop
- Adds an easy way to create HttpClient instances
- A bunch of sample cleanup/polish/simplification
The main thing here is the added ability to interop with HttpClient. We'll be making some future changes to the service invocation APIs in DaprClient to address https://github.com/dapr/dapr/issues/2342 since that issues greatly simplifies the interface we're dealing with. 
Fixes: #526
=> Add HttpClient support for Dapr service invocation

src/Dapr.Actors.AspNetCore/ActorsServiceCollectionExtensions.cs, src/Dapr.Actors/Runtime/Actor.cs, src/Dapr.Actors/Runtime/ActorHost.cs, src/Dapr.Actors/Runtime/ActorManager.cs, src/Dapr.Actors/Runtime/ActorRuntime.cs, test/Dapr.Actors.AspNetCore.Test/ActorHostingTest.cs, test/Dapr.Actors.AspNetCore.Test/Runtime/DependencyInjectionActorActivatorTests.cs, test/Dapr.Actors.Test/Runtime/ActorManagerTests.cs, test/Dapr.Actors.Test/Runtime/ActorRuntimeOptionsTests.cs, test/Dapr.Actors.Test/Runtime/ActorRuntimeTests.cs, test/Dapr.Actors.Test/Runtime/ActorTests.cs, test/Dapr.Actors.Test/Runtime/DefaultActorActivatorTests.cs
This change adds IActorProxyFactory to DI when used with ASP.NET Core,
and makes it also available as a property on the Actor base class. This
way if you've configured the ActorRuntimeOptions with your JSON
settings, its easy to have them picked up in Actors client use cases as
well.
This doesn't quite go all the way to unifying the settings with
DaprClient - we don't want to make a change that disruptive this close
to release.
Fixes: #532
=> Add IActorProxyFactory to DI

samples/Client/DaprClient/InvokeServiceGrpcExample.cs, src/Dapr.Client/DaprClientGrpc.cs, test/Dapr.Client.Test/PublishEventApiTest.cs
1. grpc sample needs a small fix.
2. runtime behavior defaults the data content type to text. Needs to be explicitly set by the sdk
=> fixes for getting the samples to work

src/Dapr.Actors/Runtime/Actor.cs, src/Dapr.Actors/Runtime/ActorHost.cs, src/Dapr.Actors/Runtime/ActorManager.cs, src/Dapr.Actors/Runtime/ActorStateManager.cs, test/Dapr.Actors.AspNetCore.Test/Runtime/DependencyInjectionActorActivatorTests.cs, test/Dapr.Actors.Test/ApiTokenTests.cs, test/Dapr.Actors.Test/DaprHttpInteractorTest.cs, test/Dapr.Actors.Test/Runtime/ActorRuntimeOptionsTests.cs, test/Dapr.Actors.Test/Runtime/ActorTests.cs, test/Dapr.Actors.Test/Runtime/DefaultActorActivatorTests.cs
Changes ActorHost constructor to be public again. Now the state manager
and http interactor are set via properties. This means that code in unit
tests won't be able to cover the methods that interact with timers or
reminders - however this was already the case. Testing state management
is covered by replacing the `IActorStateManager` with a mock.
Logged an issue to improve this.
Also added validation. If you try to use something that's not fully
initialized it will result in an exception with a meaningful message
instead of a null reference.
Also fixed some sources of indeterminism in our tests. This is still
pretty fragile, but for now the tests will at least be reliable.
We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to …
=> Make Actors unit testable

README.md
1. The official name for .NET starting version 5.0 does not include word Core
2. Used the appropriate link (the previous one has been redirected anyway)
3. Put SDK in the right position in the sentence
n/a
=> Updated README.md with .NET 5 wording, link

.github/workflows/itests.yml, .github/workflows/sdk_build.yml
Unfortunately this action requires permissions that a workflow running
for a fork does not have. You can see an example of this failing here:
https://github.com/dapr/dotnet-sdk/pull/617/checks?check_run_id=2033224542
=> Diable TRX parser on forks

src/Dapr.AspNetCore/CloudEventsMiddleware.cs, src/Dapr.AspNetCore/CloudEventsMiddlewareOptions.cs, src/Dapr.AspNetCore/DaprApplicationBuilderExtensions.cs, test/Dapr.AspNetCore.IntegrationTest.App/DaprController.cs, test/Dapr.AspNetCore.IntegrationTest/CloudEventsIntegrationTest.cs, test/Dapr.AspNetCore.IntegrationTest/SubscribeEndpointTest.cs, test/Dapr.AspNetCore.Test/CloudEventsMiddlewareTest.cs
This change teaches the cloud events middleware to JSON-decode non-JSON
content when it appears in the `data` attribute in a cloud event.
There are three cases for cloud events that matter:
- data is used, content is a JSON object, datacontentype is JSON
- data is used, content is a JSON string, dataconenttype != JSON
- data_base64 is used, content is base64 bytes
We weren't handling the second of this. If you submitted the content:
`"data": "hello, "\world!\""` with datacontenttype = text/plain
You would end up with `"hello, \"world!\""` in the request body instead
of `hello, "world!"`.
This is a very subtle case, and I'm trying to fix it before users couple
their code to the wrong behavior. Since this is technically a breaking
change, I've added a opt-out so you can restore the buggy …
=> Support non-JSON text in cloud events middleware

src/Dapr.Extensions.Configuration/DaprSecretStoreConfigurationExtensions.cs, src/Dapr.Extensions.Configuration/DaprSecretStoreConfigurationProvider.cs, src/Dapr.Extensions.Configuration/DaprSecretStoreConfigurationSource.cs, test/Dapr.Extensions.Configuration.Test/DaprSecretStoreConfigurationProviderTest.cs
This PR proposes the addition of a `CustomDelimiters` property. The custom delimiters can be used in two ways:
```csharp
.AddDaprSecretStore("store", daprClient, new[] { "--", "≡" }) // Example of multiple delimiters
```
or
```csharp
.AddDaprSecretStore((conf) =>
{
conf.Store = "store";
conf.Client = daprClient;
conf.CustomDelimiters = new[] { "--", "≡" }; // Example of multiple delimiters
})
```
This preserves the double underscore replacement regardless of the developer defining any custom delimiters or not. Documentation will be added after getting some initial opinion on this.
This PR closes issue: #627
=> [WIP] Added support for custom delimiters in secret keys.

src/Dapr.Client/Constants.cs, src/Dapr.Client/DaprClientGrpc.cs
Remove hardcoded application/json in favour of MediaTypeNames and use ContentTypeApplicationJson property.
#663
=> Remove hardcoded application/json in favour of MediaTypeNames and use ContentTypeApplicationJson property

src/Dapr.Actors/Builder/MethodDispatcherBuilder.cs, test/Dapr.Actors.Test/ActorCodeBuilderTests.cs
Call `Type.GetTypeFromHandle` when calling `IActorRequestMessageBody.GetParameter`
The code that generates the `IActorRequestMessageBody` parameter setup for the dispatched call is technically incorrect, as it passes a `RuntimeTypeHandle` to a method expecting `Type`. The correct thing to do is to call `Type.GetTypeHandle` first to perform the conversion.
It looks like RyuJIT is now validating this, where it wasn't before. It is possible the 5.0 was automatically doing the coercion, or would have crashed if the branch was ever executed (it's pretty likely that this branch has never been executed).
The test will only fail when the test project and global.json are configured for the 6.0 SDK.
We strive to have all PR being opened based on an issue, where the problem or feature have been …
=> fix: InvalidProgramException under ASP.Net 6.0

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-howto.md
Moved the UseHttpsRedirection to the else block of the IsDevelopment
check, and add a comment describing why.
The Dapr runtime reports and error and aborts the request after an HTTP
redirection. By default ASP.Net Core uses port 5000 for HTTP, and port
5001 for HTTPs. This means that if the instructions are followed exactly
the example won't work. The VSCode extension also breaks.
The alternative is to update all the docs with port 5001 instead, in addition to the VSCode extension defaults.
=> docs fix: only UseHttpsRedirection for non-dev env

src/Dapr.Actors/Runtime/ActorManager.cs
Non-reentrant actors can utilize their state manager's cache
for repeated calls. They should still be able to do this unless
using reentrancy.
* [] Created/updated tests
=> Only isolate state when using reentrancy

examples/AspNetCore/GrpcServiceSample/GrpcServiceSample.csproj, examples/Client/PublishSubscribe/PublishSubscribe.csproj, examples/Client/ServiceInvocation/ServiceInvocation.csproj, examples/Client/StateManagement/StateManagement.csproj, src/Dapr.Client/Dapr.Client.csproj, test/Dapr.Client.Test/Dapr.Client.Test.csproj
Updating grpc for arm64 support (see: https://grpc.io/blog/grpc-on-arm64/#overview-of-grpc-and-protobuf-support-on-arm64-linux )
Please reference the issue this PR will close: #729
=> Update Grpc to 2.38.1 which has arm64 support

daprdocs/content/en/dotnet-sdk-docs/dotnet-troubleshooting/dotnet-troubleshooting-pubsub.md, examples/AspNetCore/ControllerSample/Controllers/SampleController.cs, examples/AspNetCore/ControllerSample/CustomTopicAttribute.cs, examples/AspNetCore/ControllerSample/TransactionV2.cs, src/Dapr.AspNetCore/DaprEndpointRouteBuilderExtensions.cs, src/Dapr.AspNetCore/ITopicMetadata.cs, src/Dapr.AspNetCore/Subscription.cs, src/Dapr.AspNetCore/TopicAttribute.cs, src/Dapr.Client/Protos/dapr/proto/dapr/v1/appcallback.proto, test/Dapr.AspNetCore.IntegrationTest.App/CustomTopicAttribute.cs, test/Dapr.AspNetCore.IntegrationTest.App/DaprController.cs, test/Dapr.AspNetCore.IntegrationTest/SubscribeEndpointTest.cs
Add PubSub routing per dapr/dapr#3406.
Example usage
```C#
[Topic("pubsub", "transactions", "event.type == \"withdraw.v2\"", 1)]
[HttpPost("withdraw")]
public async Task<ActionResult> Withdraw(...)
```
Part of dapr/dapr#2582
=> Adding match and priority to TopicAttribute for PubSub routing.

src/Dapr.AspNetCore/DaprEndpointRouteBuilderExtensions.cs
There was an off-by-one bug in the check for duplicate default subscriptions for a given topic/pubsub.
Closes #760
=> Fixing falsely logged default subscription message

src/Dapr.Actors/Runtime/ActorRuntimeOptions.cs
When "dapr_api_token" is specified in the environment variable, actor.statemanager cannot correctly set "dapr-api-token" in the request header。
#767
* ~~[ ] Extended the documentation~~ this is a bug, don't need update documentation
=> Fix StateManager can't get dapr-api-token header.

all.sln, src/Dapr.Actors.AspNetCore/ActorsEndpointRouteBuilderExtensions.cs, src/Dapr.Actors/Runtime/ActorManager.cs, test/Dapr.E2E.Test.Actors/RegressionActor/IRegression762Actor.cs, test/Dapr.E2E.Test.Actors/RegressionActor/StateCall.cs, test/Dapr.E2E.Test.App.ReentrantActor/Actors/ReentrantActor.cs, test/Dapr.E2E.Test.App.ReentrantActor/Dapr.E2E.Test.App.ReentrantActors.csproj, test/Dapr.E2E.Test.App.ReentrantActor/Program.cs, test/Dapr.E2E.Test.App.ReentrantActor/Startup.cs, test/Dapr.E2E.Test.App.ReentrantActor/appsettings.Development.json, test/Dapr.E2E.Test.App.ReentrantActor/appsettings.json, test/Dapr.E2E.Test.App/Actors/Regression762Actor.cs, test/Dapr.E2E.Test.App/Startup.cs, test/Dapr.E2E.Test/ActorRuntimeChecker.cs, test/Dapr.E2E.Test/Actors/E2ETests.ReentrantTests.cs, test/Dapr.E2E.Test/Actors/E2ETests.Regression762Tests.cs, test/Dapr.E2E.Test/Dapr.E2E.Test.csproj, test/Dapr.E2E.Test/DaprTestAppLifecycle.cs, test/Dapr.E2E.Test/E2ETests.cs
When an actor call fails, it is imperative that the state is reset.
In the remoting path, we were catching the exception and returning
an error response instead of propagating the exception. Without this,
the error path was never triggered. This allowed for state from
failed requests to persist on subsequent requests.
https://github.com/dapr/dotnet-sdk/issues/762
Please reference the issue this PR will close: #762
=> Fix issue where state did not reset on actor error

examples/Actor/DemoActor/Properties/launchSettings.json, examples/Actor/README.md
The actors example was failing due to the port number. Therefore, the application port number is modified for actors examples both in the code as well as the readme file to make the examples run successfully.
=> Changed application port number for actors example

.github/workflows/itests.yml, .github/workflows/sdk_build.yml, test/Dapr.E2E.Test/DaprTestApp.cs
Include .NET 5 in all builds and check test status. The tests were only showing as failed in `master` as the report step doesn't actually run in PRs.
=> Include .NET 5 in all builds and check test status

src/Dapr.Actors/Runtime/ActorHost.cs, test/Dapr.Actors.AspNetCore.Test/Runtime/DependencyInjectionActorActivatorTests.cs
The property "JsonSerializerOptions" in the class "ActorHost" is always null due to missing assignment in the constructor.
Please reference the issue this PR will close: #814
=> Fix missing assignment

examples/AspNetCore/SecretStoreConfigurationProviderSample/Program.cs, src/Dapr.Client/DaprClient.cs, src/Dapr.Client/DaprClientGrpc.cs, src/Dapr.Extensions.Configuration/DaprSecretStoreConfigurationExtensions.cs, src/Dapr.Extensions.Configuration/DaprSecretStoreConfigurationProvider.cs, src/Dapr.Extensions.Configuration/DaprSecretStoreConfigurationSource.cs, test/Dapr.Client.Test/DaprClientTest.InvokeMethodAsync.cs, test/Dapr.Extensions.Configuration.Test/DaprSecretStoreConfigurationProviderTest.cs
The secret store configuration provider was trying to access Dapr
during the app startup. If the app started faster than Dapr, it would
get an error trying to access the secrets. This commit lets the
provider wait for the sidecar to come up before making any requests.
If the sidecar does not come up at all, we will still fail.
https://github.com/dapr/dotnet-sdk/issues/779
Please reference the issue this PR will close: #779 
=> Wait for sidecar in DaprSecretStoreConfiguration

examples/AspNetCore/GrpcServiceSample/GrpcServiceSample.csproj, examples/Client/PublishSubscribe/PublishSubscribe.csproj, examples/Client/ServiceInvocation/ServiceInvocation.csproj, examples/Client/StateManagement/StateManagement.csproj, src/Dapr.Client/Dapr.Client.csproj, test/Dapr.Client.Test/Dapr.Client.Test.csproj, test/Dapr.E2E.Test/Dapr.E2E.Test.csproj
Update Google.Protobuf to 3.15.
This covers the vulnerability seen here: https://github.com/advisories/GHSA-77rm-9x9h-xj3g
Please reference the issue this PR will close: Chore
=> Update Google.Protobuf to 3.15

src/Dapr.Actors/Client/ActorProxyOptions.cs, src/Dapr.Actors/Runtime/ActorRuntimeOptions.cs, src/Dapr.AspNetCore/DaprAuthenticationBuilderExtensions.cs, src/Dapr.AspNetCore/DaprAuthenticationHandler.cs, src/Dapr.AspNetCore/DaprAuthenticationOptions.cs, src/Dapr.Client/DaprClient.cs, src/Dapr.Client/DaprClientBuilder.cs, src/Dapr.Client/InvocationHandler.cs, src/Shared/DaprDefaults.cs, test/Dapr.E2E.Test.App/Controllers/TestController.cs, test/Dapr.E2E.Test.App/Startup.cs, test/Dapr.E2E.Test/DaprCommand.cs, test/Dapr.E2E.Test/DaprTestApp.cs, test/Dapr.E2E.Test/ServiceInvocation/E2ETests.ServiceInvocationTests.cs
Fix App API Token support
docs: https://docs.dapr.io/operations/security/app-api-token/
According to the documentation, DaprAuthenticationOptions.Token should read the value of the APP_API_TOKEN environment variable, but currently it reads the value of the DAPR_API_TOKEN environment variable.
#835
=> Fix App API token authentication

src/Dapr.AspNetCore/DaprServiceCollectionExtensions.cs
…gleton
Signed-off-by: zhenlei520 <wangzhenlei520@gmail.com>
I hope that AddDaprClient can be changed to TryAddSingleton. Although the AddDaprClient method only adds DaprClient to the current class library once, if other class libraries also add DaprClient and then use Dapr.AspNetCore, DaprClient will be added again.
=> Fix Adds DaprClient in Dapr.AspNetCore from AddSingleton to TryAddSingleton

examples/Actor/ActorClient/Program.cs, examples/Actor/DemoActor/DemoActor.cs, examples/Actor/DemoActor/appsettings.json, examples/Actor/IDemoActor/IDemoActor.cs, src/Dapr.Actors/Runtime/Actor.cs, src/Dapr.Actors/Runtime/ActorReminder.cs, src/Dapr.Actors/Runtime/ActorReminderOptions.cs, src/Dapr.Actors/Runtime/ActorTimer.cs, src/Dapr.Actors/Runtime/ActorTimerOptions.cs, src/Dapr.Actors/Runtime/DefaultActorTimerManager.cs, src/Dapr.Actors/Runtime/IActorReminder.cs, src/Dapr.Actors/Runtime/ReminderInfo.cs, src/Dapr.Actors/Runtime/TimerInfo.cs, test/Dapr.Actors.Test/Runtime/ActorReminderInfoTests.cs, test/Dapr.E2E.Test.Actors/Reminders/IReminderActor.cs, test/Dapr.E2E.Test.Actors/Reminders/State.cs, test/Dapr.E2E.Test.Actors/Timers/ITimerActor.cs, test/Dapr.E2E.Test.Actors/Timers/State.cs, test/Dapr.E2E.Test.App/Actors/ReminderActor.cs, test/Dapr.E2E.Test.App/Actors/TimerActor.cs, test/Dapr.E2E.Test/Actors/E2ETests.ReminderTests.cs, test/Dapr.E2E.Test/Actors/E2ETests.TimerTests.cs
This commit adds the TTL field to Actor reminders/timers. This allows
reminders and timers to expire after a given TimeSpan instead of
having to be manually deleted.
https://github.com/dapr/dotnet-sdk/issues/788
Please reference the issue this PR will close: #788 
=> Add Actor Reminder/Timer TTL support

src/Dapr.Actors.AspNetCore/ActorsEndpointRouteBuilderExtensions.cs, test/Dapr.Actors.AspNetCore.IntegrationTest/Dapr.Actors.AspNetCore.IntegrationTest.csproj, test/Dapr.Actors.AspNetCore.IntegrationTest/HostingTests.cs
Signed-off-by: Marcos Candeia <marrcooos@gmail.com>
Allowing anonymous calls to the /healthz endpoint when exposing actors' health checks.
Please reference the issue this PR will close: #908 
=> FIX Allow actor healthz endpoint are now always AllowAnonymous

examples/AspNetCore/GrpcServiceSample/GrpcServiceSample.csproj, examples/Client/PublishSubscribe/PublishSubscribe.csproj, examples/Client/ServiceInvocation/ServiceInvocation.csproj, examples/Client/StateManagement/StateManagement.csproj, src/Dapr.Client/Dapr.Client.csproj, test/Dapr.Client.Test/Dapr.Client.Test.csproj, test/Dapr.E2E.Test/Dapr.E2E.Test.csproj
Signed-off-by: Marcos Candeia <marrcooos@gmail.com>
Upgrade grpc.tools version to 2.47.0 to support arm64 architecture
Please reference the issue this PR will close:  #919 
=> Upgrade grpc.tools version to 2.47.0 for supporting arm64 architecture

examples/AspNetCore/ControllerSample/Controllers/SampleController.cs, examples/AspNetCore/ControllerSample/CustomTopicAttribute.cs, examples/AspNetCore/ControllerSample/README.md, examples/AspNetCore/RoutingSample/README.md, examples/AspNetCore/RoutingSample/Startup.cs, src/Dapr.AspNetCore/DaprEndpointConventionBuilderExtensions.cs, src/Dapr.AspNetCore/DaprEndpointRouteBuilderExtensions.cs, src/Dapr.AspNetCore/IDeadLetterTopicMetadata.cs, src/Dapr.AspNetCore/ITopicMetadata.cs, src/Dapr.AspNetCore/Subscription.cs, src/Dapr.AspNetCore/TopicAttribute.cs, src/Dapr.AspNetCore/TopicOptions.cs, src/Dapr.Client/Protos/dapr/proto/dapr/v1/appcallback.proto, test/Dapr.AspNetCore.IntegrationTest.App/CustomTopicAttribute.cs, test/Dapr.AspNetCore.IntegrationTest.App/DaprController.cs, test/Dapr.AspNetCore.IntegrationTest/SubscribeEndpointTest.cs
Closes https://github.com/dapr/dotnet-sdk/issues/897
Signed-off-by: Yash Nisar <yashnisar@microsoft.com>
Add support for dead letter topic for the dotnet sdk
Please reference the issue this PR will close: https://github.com/dapr/dotnet-sdk/issues/897
=> Add dead letter topic support

examples/Client/README.md
Signed-off-by: Amulya Varote <amulyavarote@microsoft.com>
=> Added new links to client folder in example

src/Dapr.AspNetCore/TopicMetadataAttribute.cs, test/Dapr.AspNetCore.IntegrationTest.App/DaprController.cs, test/Dapr.AspNetCore.IntegrationTest/SubscribeEndpointTest.cs
Signed-off-by: saberwang <saberwang@hotmail.com>
=> topicmetadata should allow adding empty strings

examples/AspNetCore/ControllerSample/Controllers/SampleController.cs, examples/AspNetCore/RoutingSample/Startup.cs
Fixes https://github.com/dapr/dotnet-sdk/issues/936
Signed-off-by: Yash Nisar <yashnisar@microsoft.com>
Currently, we do support logging but the log level is debug in pubsub examples. Since the default log level in `appsettings.json` is information, logging is suppressed. We need to enable logging by replacing `logger.LogDebug(...)` by `logger.LogInformation(...)`
https://github.com/dapr/dotnet-sdk/issues/936
=> Change log level to information in pubsub examples

.github/workflows/dapr-bot.yml
Closes https://github.com/dapr/dotnet-sdk/issues/933
Signed-off-by: Yash Nisar <yashnisar@microsoft.com>
Add dapr-bot support to assign issues
Tested it with my own personal access token here: https://github.com/yash-nisar/dotnet-sdk/issues/1
https://github.com/dapr/dotnet-sdk/issues/933
Please reference the issue this PR will close: https://github.com/dapr/dotnet-sdk/issues/933
=> Add dapr-bot support to assign issues

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-howto.md
Signed-off-by: Hannah Hunter <hannahhunter@microsoft.com>
Remove version flags from command examples
dapr/docs#2831
=> [docs] Remove version flags

README.md, daprdocs/content/en/dotnet-sdk-docs/_index.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-client/_index.md
Signed-off-by: Hannah Hunter <hannahhunter@microsoft.com>
Per discussion w @msfussell - restructuring landing page to be more navigable and consistent with JS and Python structure.
PR will close: #880 
=> Restructure .NET sdk landing page

examples/Actor/ActorClient/Program.cs, examples/Actor/DemoActor/DemoActor.cs, examples/Actor/IDemoActor/IDemoActor.cs, src/Dapr.Actors/Resources/SR.Designer.cs, src/Dapr.Actors/Resources/SR.resx, src/Dapr.Actors/Runtime/Actor.cs, src/Dapr.Actors/Runtime/ActorReminder.cs, src/Dapr.Actors/Runtime/ActorReminderOptions.cs, src/Dapr.Actors/Runtime/ConverterUtils.cs, src/Dapr.Actors/Runtime/DefaultActorTimerManager.cs, src/Dapr.Actors/Runtime/ReminderInfo.cs, test/Dapr.Actors.Test/DaprFormatTimeSpanTests.cs, test/Dapr.Actors.Test/Runtime/ActorReminderInfoTests.cs, test/Dapr.Actors.Test/Runtime/DefaultActorTimerManagerTests.cs, test/Dapr.Actors.Test/TestDaprInteractor.cs, test/Dapr.E2E.Test.Actors/Reminders/IReminderActor.cs, test/Dapr.E2E.Test.App/Actors/ReminderActor.cs, test/Dapr.E2E.Test/Actors/E2ETests.ReminderTests.cs
Closes https://github.com/dapr/dotnet-sdk/issues/702
Signed-off-by: Yash Nisar <yashnisar@microsoft.com>
Add support for reptition and ISO 8601 for reminders
Please reference the issue this PR will close: https://github.com/dapr/dotnet-sdk/issues/702
* [] Extended the documentation
=> Add support for repetition and ISO 8601 for reminders

src/Dapr.Workflow/Dapr.Workflow.csproj, src/Dapr.Workflow/WorkflowEngineClient.cs, src/Dapr.Workflow/WorkflowServiceCollectionExtensions.cs, test/Dapr.E2E.Test/Dapr.E2E.Test.csproj
An issue was discovered that prevents the Dapr Workflow authoring SDK from working on ARM64-based processors, including M1 and M2 macs. When trying, the following exception is encountered:
```
== APP == Unhandled exception. System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: /Users/xxx/src/xxx/dotnet-sdk/bin/Debug/examples/WorkflowWebApp/net6.0/libgrpc_csharp_ext.arm64.dylib,/Users/xxx/src/xxx/dotnet-sdk/bin/Debug/examples/WorkflowWebApp/net6.0/runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib,/Users/xxx/src/xxx/dotnet-sdk/bin/Debug/examples/WorkflowWebApp/net6.0/../../runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib
== APP ==    at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] …
```
=> Update DurableTask SDK dependency to get ARM64 compatibility

src/Dapr.Workflow/Dapr.Workflow.csproj, src/Dapr.Workflow/WorkflowEngineClient.cs, src/Dapr.Workflow/WorkflowServiceCollectionExtensions.cs, test/Dapr.E2E.Test/Dapr.E2E.Test.csproj
Cherry-pick from https://github.com/dapr/dotnet-sdk/pull/1024 to get this into the v1.10 release.
=> Update DurableTask SDK dependency to get ARM64 compatibility (#1024)

all.sln, examples/Workflow/README.md, examples/Workflow/WorkflowConsoleApp/Activities/NotifyActivity.cs, examples/Workflow/WorkflowConsoleApp/Activities/ProcessPaymentActivity.cs, examples/Workflow/WorkflowConsoleApp/Activities/ReserveInventoryActivity.cs, examples/Workflow/WorkflowConsoleApp/Models.cs, examples/Workflow/WorkflowConsoleApp/Workflows/OrderProcessingWorkflow.cs, examples/Workflow/WorkflowUnitTest/OrderProcessingTests.cs, examples/Workflow/WorkflowUnitTest/WorkflowUnitTest.csproj, src/Dapr.Workflow/DaprWorkflowContext.cs, src/Dapr.Workflow/WorkflowContext.cs, src/Dapr.Workflow/WorkflowRuntimeOptions.cs
An early user of Dapr Workflow pointed out that they aren't able to unit test their workflows. This PR addresses that problem by:
1. Making `WorkflowContext` a mockable abstract base class
2. Providing an example app that shows how to unit test workflows
The new unit test project isn't meant as an actual test to be run by us, but as a reference for developers so that they can learn how to write their own unit tests for workflows.
Note that the unit test project references the workflow console app sample, so I made many of the types in that sample `public` so that they could be easily tested from another project.
I also found a bug while refactoring the `WorkflowContext` - calls to `WorkflowContext.SendEvent()` would have resulted in a `StackOverflowException`. That is fixed in this PR …
=> Enable unit testing for Dapr Workflows

src/Dapr.Workflow/WorkflowServiceCollectionExtensions.cs
Use ignored variable in WorkflowServiceCollectionExtensions.AddDaprWorkflow
Use ignored variable in `WorkflowServiceCollectionExtensions.AddDaprWorkflow` to remove duplication. (biggest nit ever)
Please reference the issue this PR will close: #1055
=> fix: Use ignored variable in WorkflowServiceCollectionExtensions.AddDaprWorkflow

examples/Actor/ActorClient/Program.cs, examples/Actor/DemoActor/DemoActor.cs, examples/Actor/IDemoActor/IDemoActor.cs, src/Dapr.Actors/DaprHttpInteractor.cs, src/Dapr.Actors/IDaprInteractor.cs, src/Dapr.Actors/Runtime/Actor.cs, src/Dapr.Actors/Runtime/ActorTestOptions.cs, src/Dapr.Actors/Runtime/ActorTimerManager.cs, src/Dapr.Actors/Runtime/DefaultActorTimerManager.cs, src/Dapr.Actors/Runtime/ReminderInfo.cs, test/Dapr.Actors.Test/ActorUnitTestTests.cs, test/Dapr.Actors.Test/TestDaprInteractor.cs, test/Dapr.E2E.Test.Actors/Reminders/IReminderActor.cs, test/Dapr.E2E.Test.App/Actors/ReminderActor.cs, test/Dapr.E2E.Test/Actors/E2ETests.ReminderTests.cs
It adds the get actor reminder API in dotnet-sdk
Please reference the issue this PR will close: #772 
=> adding get actor reminder API

examples/Actor/ActorClient/Program.cs, examples/Actor/DemoActor/DemoActor.cs, examples/Actor/IDemoActor/IDemoActor.cs, src/Dapr.Actors/DaprHttpInteractor.cs, src/Dapr.Actors/IDaprInteractor.cs, src/Dapr.Actors/Runtime/Actor.cs, src/Dapr.Actors/Runtime/ActorTestOptions.cs, src/Dapr.Actors/Runtime/ActorTimerManager.cs, src/Dapr.Actors/Runtime/DefaultActorTimerManager.cs, src/Dapr.Actors/Runtime/ReminderInfo.cs, test/Dapr.Actors.Test/ActorUnitTestTests.cs, test/Dapr.Actors.Test/TestDaprInteractor.cs, test/Dapr.E2E.Test.Actors/Reminders/IReminderActor.cs, test/Dapr.E2E.Test.App/Actors/ReminderActor.cs, test/Dapr.E2E.Test/Actors/E2ETests.ReminderTests.cs
This PR cherry-picks release-1.11 changes to master. 
=> Merge release-1.11 to master

.github/workflows/itests.yml, src/Dapr.Workflow/Dapr.Workflow.csproj, src/Dapr.Workflow/DaprWorkflowClient.cs
In https://github.com/dapr/dapr/issues/6614, a user observed that the `RaiseEventAsync` method was always resulting in a null payload in the workflow code. This PR fixes the issue, which is isolated to the Dapr Workflow SDK.
I also made a couple other small changes as part of this PR:
* Bumped the Durable Task SDK dependency to the latest patch release.
* Changed the default `getInputsAndOutputs` to `true` for the workflow status query APIs (I decided to do this to improve usability after some frustration while setting up the local repro for the raise event issue)
I also updated the Workflow SDK nuget version to `0.3.0`.
Closes https://github.com/dapr/dapr/issues/6614
=> [Workflow] Fix issue with ignored external event payload

daprdocs/content/en/dotnet-sdk-docs/_index.md
This PR adds cascading metadata so the edit/view page buttons work as expected
Partially addresses https://github.com/dapr/docs/issues/1895
=> [docs] Add cascading metadata information

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-howto.md
See title
PR will close: dapr/docs#1426
=> [docs] Remove invalid code line in example

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-howto.md
It adds the get  actor reminder API in docs. The API implementation is merged in release-1.11 in #1103. 
=> adding get actor reminder API in docs

src/Dapr.Client/DaprClientGrpc.cs
Implements the changes for https://github.com/dapr/dotnet-sdk/issues/1144
I followed the same pattern that is used in `CreateInvokeMethodRequest` which is the only other related to the use of the http client being used for the healthz requests.
Please reference the issue this PR will close: #1144
I think this changes don't require docs or test changes... existing tests and docs already cover this behaviour
=> set dapr-api-token to healthz requests when needed

test/Dapr.E2E.Test.App/Startup.cs, test/Dapr.E2E.Test/Workflows/WorkflowTest.cs
Previously, raising multiple events of the same name in parallel in workflow led to a series of events being incomplete. A change was made to durable task framework in the .NET SDK to fix this issue. This PR adds in a test to ensure that the fix works in this SDK as well.
Please reference the issue this PR will close: #_[[1129](https://github.com/dapr/dotnet-sdk/issues/1129)]_
* [ X] Created/updated tests
=> Adding in new test for parallel raise events in workflow

test/Dapr.E2E.Test.App/Startup.cs, test/Dapr.E2E.Test/Workflows/WorkflowTest.cs
Cherry pick change from master to release-1.12.
=> Adding in new test for parallel raise events in workflow (#1155)

examples/Workflow/WorkflowConsoleApp/WorkflowConsoleApp.csproj, examples/Workflow/WorkflowUnitTest/WorkflowUnitTest.csproj, properties/dapr_managed_netcore.props, src/Dapr.Workflow/Dapr.Workflow.csproj
Now that .NET 6 is the minimum target for the SDK, we can roll forward the C# language version to 10, which has some useful new features.
Please reference the issue this PR will close: #1181
=> Consolidate C# language version to 10.

examples/Actor/ActorClient/Program.cs, examples/Actor/DemoActor/DemoActor.cs, examples/Actor/IDemoActor/IDemoActor.cs
Updates the actor reminder example to resolve an unexpected exception. The actor was attempting to directly return an `IActorReminder` instance but the underlying type was not intended to be used outside of the actor and was not designed to be serialized.  Instead, its properties are now copied to a separate type which is returned to the caller.  A couple of other changes were made to the client project to correct assumptions about return types.
Please reference the issue this PR will close: #1177 
=> Update actor reminder example.

src/Dapr.Workflow/WorkflowLoggingService.cs, src/Dapr.Workflow/WorkflowRuntimeOptions.cs, src/Dapr.Workflow/WorkflowServiceCollectionExtensions.cs, test/Dapr.E2E.Test.App/Dapr.E2E.Test.App.csproj, test/Dapr.E2E.Test.App/Program.cs, test/Dapr.E2E.Test.App/Startup.cs, test/Dapr.E2E.Test/Workflows/WorkflowTest.cs
Added in basic logging for workflow to log the registered activities and registered workflows.
Please reference the issue this PR will close: [ #_[1170]_](https://github.com/dapr/dotnet-sdk/issues/1170)
=> Initial implementation for workflow log tracing

.github/workflows/itests.yml, .github/workflows/sdk_build.yml, src/Dapr.Actors.AspNetCore/ActorsEndpointRouteBuilderExtensions.cs, src/Dapr.Actors.AspNetCore/Dapr.Actors.AspNetCore.csproj, src/Dapr.Actors/Dapr.Actors.csproj, src/Dapr.AspNetCore/Dapr.AspNetCore.csproj, src/Dapr.AspNetCore/DaprAuthenticationHandler.cs, src/Dapr.Client/Dapr.Client.csproj, src/Dapr.Client/DaprApiException.cs, src/Dapr.Client/DaprException.cs, src/Dapr.Extensions.Configuration/Dapr.Extensions.Configuration.csproj, src/Dapr.Workflow/Dapr.Workflow.csproj, src/Directory.Build.props, test/Dapr.Actors.AspNetCore.IntegrationTest.App/Dapr.Actors.AspNetCore.IntegrationTest.App.csproj, test/Dapr.Actors.AspNetCore.IntegrationTest/Dapr.Actors.AspNetCore.IntegrationTest.csproj, test/Dapr.Actors.AspNetCore.Test/Dapr.Actors.AspNetCore.Test.csproj, test/Dapr.Actors.Test/Dapr.Actors.Test.csproj, test/Dapr.AspNetCore.IntegrationTest.App/Dapr.AspNetCore.IntegrationTest.App.csproj, test/Dapr.AspNetCore.IntegrationTest/Dapr.AspNetCore.IntegrationTest.csproj, test/Dapr.AspNetCore.Test/Dapr.AspNetCore.Test.csproj, test/Dapr.Client.Test/Dapr.Client.Test.csproj, test/Dapr.E2E.Test.Actors/Dapr.E2E.Test.Actors.csproj, test/Dapr.E2E.Test.App.Grpc/Dapr.E2E.Test.App.Grpc.csproj, test/Dapr.E2E.Test.App.ReentrantActor/Dapr.E2E.Test.App.ReentrantActors.csproj, test/Dapr.E2E.Test.App/Dapr.E2E.Test.App.csproj, test/Dapr.E2E.Test/Dapr.E2E.Test.csproj, test/Dapr.E2E.Test/DaprTestApp.cs, test/Dapr.Extensions.Configuration.Test/Dapr.Extensions.Configuration.Test.csproj, test/Directory.Build.props
Add explicit .NET 8 targets to Dapr .NET SDK NuGet packages.
Currently, the Dapr .NET SDK NuGet packages target only .NET 6 (except for Workflow, which also targets .NET 7).  With this change, the packages will additionally target .NET 8.
Please reference the issue this PR will close: #1187 
=> .NET 8 Support

test/Dapr.Client.Test/PublishEventApiTest.cs
I prefer the JsonSerializer retaining the `string` over `int` values for enums, so when I saw the bug reported in #1160 , I though I'd go ahead and tackle it. While I was unable to reproduce the experienced issue, I went ahead and added a unit test to the suite to prove out that this experience both works as-is and doesn't break going forward.
Please reference the issue this PR will close: #1160 
~* [ ] Code compiles correctly~
~* [ ] Extended the documentation~
=> Added unit test to validate JsonStringEnumConverter working as expected

src/Dapr.Client/DaprClient.cs
Corrected a spelling mistake in XML documentation
=> Correct spelling of "identified"

daprdocs/content/en/dotnet-sdk-docs/dotnet-workflow/dotnet-workflow-howto.md, examples/Workflow/README.md, examples/Workflow/WorkflowConsoleApp/Program.cs, examples/Workflow/WorkflowConsoleApp/demo.http
Added in logic to properly catch a CTRL+C termination input from the user to shutdown the workflow console app example.
Updated Readme
This PR will close: #_[[1189](https://github.com/dapr/dotnet-sdk/issues/1189)]_ #_[[1191](https://github.com/dapr/dotnet-sdk/issues/1191)]_
**Note that the issue of 1189 will not fully be resolved until https://github.com/microsoft/durabletask-dotnet/issues/249 is resolved.
=> Updating the workflow console app example program to allow for CTRL+C to properly terminate the program, and Readme updates

src/Dapr.Actors.AspNetCore/ActorsEndpointRouteBuilderExtensions.cs, src/Dapr.Actors/Runtime/ActorManager.cs, test/Dapr.Actors.Test/Runtime/ActorRuntimeTests.cs
Enable use of `CancellationToken` in actor interfaces/implementations when clients use the non-remoting proxy.  This, when combined with #1158, would enable both clients and implementations to use the same interface definition.
Also ensures that the `CancellationToken` from the HTTP request is pushed down into the handling and actor logic.
> :warning: When using this capability, clients cannot use the remoting-based proxy for method invocation.
Please reference the issue this PR will close: #1201 
=> Enable `CancellationToken` for non-remoting actor implementations

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-howto.md
Fix example output to not repeat "Success"
Status is "Success" is repeated in output from example.
=> Fix example dotnet-actors-howto.md

daprdocs/content/en/dotnet-sdk-docs/dotnet-client/_index.md
=> Update _index.md by fixing broken link

examples/Workflow/WorkflowConsoleApp/Program.cs
=> use daprWorkflowClient instead of daprClient in workflow sample

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-serialization.md
This is my first draft of a new page in the documentation detailing how serialization works using the Dapr .NET Actors SDK today. It's my response to the issue raised https://github.com/dapr/dotnet-sdk/issues/679 which is marked as a bug, but reflects a misunderstanding of how the serialization engine handles records. My goal with adding this page is to provide an upfront resource for developers using actors to understand why serialization may not be working as expected out of the box and provide not only a solution, but an explanation.
I detail how serialization is performed to illustrate the benefits to either going the parameterless constructor route or decorating types and members with the applicable attributes and then share my recommendation to use attributes and why. I dive through …
=> Docs: Actor serialization documentation

src/Dapr.Actors/Runtime/ActorManager.cs, test/Dapr.E2E.Test.Actors/WeaklyTypedTesting/DerivedResponse.cs, test/Dapr.E2E.Test.Actors/WeaklyTypedTesting/IWeaklyTypedTestingActor.cs, test/Dapr.E2E.Test.Actors/WeaklyTypedTesting/ResponseBase.cs, test/Dapr.E2E.Test.App/Actors/WeaklyTypedTestingActor.cs, test/Dapr.E2E.Test.App/Startup.cs, test/Dapr.E2E.Test/Actors/E2ETests.WeaklyTypedTests.cs
In .NET 7.0 or later an operation on an actor invoked using a weakly-typed actor client should support a polymorphic response. The response json should include a type discriminator property to allow for polymorphic deserialization by the actor client. The weakly-typed actor client must polymorphically deserialize the response when invoking `InvokeMethodAsync<ResponseBase>` on the weakly-typed actor client. This should yield a `DerivedResponse` instance. Note that invoking `InvokeMethodAsync<DerivedResponse>` is not polymorphic deserialization.
While System.Text.Json support polymorphic deserialization from .NET 7, the Dapr .NET Actors SDK only builds .NET 6 and .NET 8, but not .NET 7. The E2E tests on the other hand do still build .NET 6, .NET 7 and .NET 8. As a consequence the .NET 7 …
=> Weakly-typed actors should support polymorphic response and null response

.github/workflows/sdk_build.yml
The handoff between the build step and the publish step of the CI/CD pipeline does not seem to be working.  I noticed that we were using the `master` version of the upload action but the `v2` version of the download action.  The action repos mention that the latest versions (v4) represent significant architectural changes from prior versions, which I speculate may be the reason for the break (i.e. the upload is using the new architecture while the download is using the old).
=> Move to v4 of the upload/download artifact actions.

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-howto.md
With the release of .NET 8, a warning for [ASP0014](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0014?view=aspnetcore-8.0) was added that suggests that routes shouldn't be registered via `app.UseEndpoints` and longer and should rather be registered directly from the built web application.
This requires no changes to the SDK itself, but the documentation should be updated to reflect the change and this PR corrects this as was pointed out by the issue in #1256.
Please reference the issue this PR will close: #1256
=> Updated docs to register actor endpoint via top-level registrations

src/Dapr.Extensions.Configuration/DaprSecretStoreConfigurationProvider.cs, test/Dapr.Extensions.Configuration.Test/DaprSecretStoreConfigurationProviderTest.cs
Applies the secret key/name transformation (if specified) only when the returned key name matches the secret key name.  If "sub keys" are returned, for example, the transformation makes no sense and results in duplicate key names.
Please reference the issue this PR will close: #1249
=> Fix for secret key transformation in multi-value scenarios

all.sln
Removed non-existent project **PublishSubscribe** because it was split into two projects in the **Client/PublishSubscribe** folder , correct path of the **Dapr.Actors.Generators** project physically located inside the **/src** folder but in the solution it was in the **examples/GeneratedActor** folder.
-
=> Removed non-existent project PublishSubscribe, correct path of the Dapr.Actors.Generators project.

src/Dapr.Client/DaprClient.cs, src/Dapr.Client/DaprClientGrpc.cs, src/Dapr.Client/Extensions/EnumExtensions.cs, src/Dapr.Client/Extensions/HttpExtensions.cs, test/Dapr.Client.Test/DaprClientTest.InvokeMethodAsync.cs, test/Dapr.Client.Test/Extensions/EnumExtensionTest.cs, test/Dapr.Client.Test/Extensions/HttpExtensionTest.cs
When a method is invoked via the Dapr service invocation building block, a query string can be passed through on the invocation URL without issue. However, when using the .NET SDK, this behavior isn't exposed anywhere. Existing overloads allow the app ID to be specified, the method named, the payload to be provided, but that's it - it's up to the developer to realize that a query string is supported, then augment the `RequestUri` property of the returned `HttpRequestMessage` to append their query string values, and proceed with the invocation.
This PR provides overloads to the invocation methods to allow an `IReadOnlyCollection<KeyValuePair<string,string>>` to be provided as the collection of key/value pairs to build/supplement the query string with. This uses a static extension method …
=> Added overload to support SDK supplying query string on invoked URL

daprdocs/content/en/dotnet-sdk-docs/dotnet-client/_index.md
Link from client doc to the 'invoke non-Dapr endpoint' how-to. 
PR will close: dapr/docs#4029
=> [Service invocation] Link to non-Dapr endpoint how-to

src/Dapr.Workflow/WorkflowState.cs
Added a missing branch to switch statement to support `WorkflowRuntimeStatus.Suspended`. Thanks to @cgillum for pointing out [where the error was](https://github.com/dapr/dotnet-sdk/issues/1215#issuecomment-2345069306).
Please reference the issue this PR will close: #1215
* [N/A] Created/updated tests
Surprising, there's no unit test package for the workflow project. This should be remedied, but isn't particularly necessary for this patch as it's quite a minor add.
=> Added missing workflow status branch

Directory.Packages.props, examples/AspNetCore/GrpcServiceSample/GrpcServiceSample.csproj, examples/Client/PublishSubscribe/BulkPublishEventExample/BulkPublishEventExample.csproj, examples/Client/PublishSubscribe/PublishEventExample/PublishEventExample.csproj, examples/Client/ServiceInvocation/ServiceInvocation.csproj, examples/Client/StateManagement/StateManagement.csproj, examples/Workflow/WorkflowUnitTest/WorkflowUnitTest.csproj, properties/dapr_managed_netcore.props, src/Dapr.Actors.Generators/Dapr.Actors.Generators.csproj, src/Dapr.Actors/Dapr.Actors.csproj, src/Dapr.Client/Dapr.Client.csproj, src/Dapr.Extensions.Configuration/Dapr.Extensions.Configuration.csproj, src/Dapr.Workflow/Dapr.Workflow.csproj, src/Directory.Build.props, test/Dapr.Actors.AspNetCore.IntegrationTest/Dapr.Actors.AspNetCore.IntegrationTest.csproj, test/Dapr.Actors.AspNetCore.Test/Dapr.Actors.AspNetCore.Test.csproj, test/Dapr.Actors.Generators.Test/CSharpSourceGeneratorVerifier.cs, test/Dapr.Actors.Generators.Test/Dapr.Actors.Generators.Test.csproj, test/Dapr.Actors.Test/Dapr.Actors.Test.csproj, test/Dapr.AspNetCore.IntegrationTest/Dapr.AspNetCore.IntegrationTest.csproj, test/Dapr.AspNetCore.Test/Dapr.AspNetCore.Test.csproj, test/Dapr.Client.Test/Dapr.Client.Test.csproj, test/Dapr.Client.Test/DaprClientTest.InvokeMethodGrpcAsync.cs, test/Dapr.Client.Test/StateApiTest.cs, test/Dapr.E2E.Test.Actors.Generators/Dapr.E2E.Test.Actors.Generators.csproj, test/Dapr.E2E.Test.App.Grpc/Dapr.E2E.Test.App.Grpc.csproj, test/Dapr.E2E.Test.App/Dapr.E2E.Test.App.csproj, test/Dapr.E2E.Test/Dapr.E2E.Test.csproj, test/Dapr.Extensions.Configuration.Test/Dapr.Extensions.Configuration.Test.csproj, test/Directory.Build.props
.NET 9 replaces the NuGet vulnerability scanner opt-in functionality with a project-wide (including transitive references) scanner by default. For some reason today, my system received this preview and I was utterly unable to build Dapr locally.
At @philliphoff 's suggestion, I've implemented central package management with transient dependency pinning across the solution and then updated all packages to the latest versions compatible with .NET 6 (as it's still supported with 1.15).
There were a few unit tests that needed a tweak because of the package updates, so they're bundled in here as well, but everything builds on my system as it should at this point. Some of the packages were wildly out of date, so this should also lend itself to at least a minor performance boost on the client as …
=> Fixed security advisory updates across dependencies (transitive and direct)

daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-serialization.md
Updated the actor serialization documentation to reflect the differences between the JSON serialization and the Data Contract serialization approaches used in the Dapr.Actors SDK, how they relate to the different actor client types and some examples of how to properly use each of them.
This addresses a comment left at https://github.com/dapr/dotnet-sdk/pull/1073#issuecomment-1952420285 and occasionally seen in Discord though doesn't have an open issue that I see.
* [N/A] Code compiles correctly
* [N/A] Created/updated tests
=> Updating actor serialization documentation

Directory.Packages.props, test/Dapr.E2E.Test.App/Dapr.E2E.Test.App.csproj
Removed `Serilog` nuget from `DirectoryPackages.props` because it can be handled as a transient dependency so you don't have to update it manually.
-
=> cleanup: Removed Serilog nuget from Directory.Packages.props

src/Dapr.Workflow/DaprWorkflowClientBuilderFactory.cs, src/Dapr.Workflow/WorkflowRuntimeOptions.cs, test/Dapr.E2E.Test.App/Startup.cs, test/Dapr.E2E.Test/DaprTestApp.cs
You can now use custom GrpcChannelOptions when using DaprWorkflow, in the same manner as was already the case when creating the DaprClient:
```
builder.Services.AddDaprWorkflow(options =>
{
options.UseGrpcChannelOptions(new GrpcChannelOptions
{
MaxReceiveMessageSize = 32 * 1024 * 1024,
MaxSendMessageSize = 32 * 1024 * 1024
});
});
```
See issue: GRPC data receive limits ([#7218](https://github.com/dapr/dapr/issues/7218))
=> Added option to override GrpcChannelOptions when adding DaprWorkflow (#7218)

.github/workflows/itests.yml, .github/workflows/sdk_build.yml
Sets the fail-fast to false for both the build and integration test workflows
=> ci: set fail-fast to false

src/Dapr.Actors.AspNetCore/ActorsServiceCollectionExtensions.cs, src/Dapr.Jobs/Extensions/DaprJobsServiceCollectionExtensions.cs, src/Dapr.Messaging/PublishSubscribe/Extensions/PublishSubscribeServiceCollectionExtensions.cs, test/Dapr.Actors.AspNetCore.Test/DaprActorServiceCollectionExtensionsTest.cs, test/Dapr.AspNetCore.Test/DaprServiceCollectionExtensionsTest.cs, test/Dapr.Jobs.Test/Extensions/DaprJobsServiceCollectionExtensionsTests.cs, test/Dapr.Messaging.Test/Extensions/PublishSubscribeServiceCollectionExtensionsTests.cs
This is a follow up to #1408 that adds lifecycle registration for the following additional clients:
- Dapr.Jobs
- Dapr.Messaging
- Dapr.Actors.AspNetCore
* [N/A] Extended the documentation - Will write documentation as part of a separate PR (likely #1409 )
=> Additional lifecycle registration changes

examples/AI/ConversationalAI/Program.cs, src/Dapr.AI/Conversation/Extensions/DaprAiConversationBuilderExtensions.cs, test/Dapr.AI.Test/Conversation/Extensions/DaprAiConversationBuilderExtensionsTest.cs, test/Dapr.Jobs.Test/Extensions/DaprJobsServiceCollectionExtensionsTests.cs
While writing up the documentation for each, I realized that the conversation builder had an inconsistency naming convention. This fixes that, the associated unit tests and example and also fixes another unit test that was incorrect in the Jobs API.
=> Conversation builder consistency changes

daprdocs/content/en/dotnet-sdk-docs/dotnet-jobs/_index.md
_index.md page for dotnet-jobs has a broken link - fixing it so that link validation in dapr/docs repo can build.
=> [docs] fix typo in link

src/Dapr.AI/Conversation/DaprConversationClient.cs, src/Dapr.AI/Conversation/DaprConversationInput.cs, src/Dapr.Protos/Protos/dapr/proto/runtime/v1/dapr.proto
This PR simply reflects [a change](https://github.com/dapr/dapr/pull/8510) made to the Conversation API protos this week.
* [N/A] Created/updated tests
* [N/A] Extended the documentation
=> Updating Conversation SDK

daprdocs/content/en/dotnet-sdk-docs/dotnet-client/_index.md
Workflow is no longer a part of the `Dapr.Client` package and as such has been removed from the documentation for it accordingly.
N/A
* [N/A] Code compiles correctly
* [N/A] Created/updated tests
=> Removed out-of-date workflow reference in docs

daprdocs/content/en/dotnet-sdk-docs/dotnet-jobs/dotnet-jobs-howto.md, examples/Jobs/JobsSample/Program.cs, src/Dapr.Jobs/Extensions/EndpointRouteBuilderExtensions.cs, test/Dapr.Jobs.Test/Extensions/EndpointRouteBuilderExtensionsTests.cs
The original implementation of the jobs mapping handler allowed the user to provide a `CancellationToken` to the mapping. This unfortunately meant that long-running jobs mappers would fail when this timeout was hit because it was globally applied instead of applied to each request invocation, as intended.
I've modified the approach to instead allow the user to pass an optional `TimeSpan` indicating a timeout value to use. As part of the mapping, a new `CancellationToken` is created using this timeout value, if provided (defaults to `CancellationToken.None` if not) so it's now performed on a per-request basis.
I've also updated the example and unit tests to go along with this.
Thanks to @siri-varma for their research in identifying this issue.
We strive to have all PR being opened based on …
=> Fix for Jobs mapping handler

src/Dapr.Actors/DaprHttpInteractor.cs, src/Dapr.Actors/IDaprInteractor.cs, src/Dapr.Actors/Runtime/DefaultActorTimerManager.cs, test/Dapr.Actors.Test/ActorUnitTestTests.cs, test/Dapr.Actors.Test/DaprHttpInteractorTest.cs, test/Dapr.Actors.Test/Runtime/DefaultActorTimerManagerTests.cs, test/Dapr.Actors.Test/TestDaprInteractor.cs
Actor reminders should return null if they aren't registered and should return a `ReminderInfo` if they are registered. According to the API documentation, this is distinguished by the status code returned:
| Status Code | Action |
| --- | --- |
| 200 | Read the actor info from the response body |
| 500 | Not available |
The original implementation of this never read the status code and instead started with a `ReminderInfo` populated with default values for each property and attempted to deserialize each property and update the value if available in the returned body. As a result, this means that the response would never be null and if not registered, the only way to determine this was to do a default check against each of the properties.
This PR changes this - if the status code is 500, …
=> Actor reminders should return null if not registered

src/Dapr.Actors/Runtime/DefaultActorTimerManager.cs, src/Dapr.Actors/Runtime/ReminderInfo.cs, test/Dapr.Actors.Test/Runtime/DefaultActorTimerManagerTests.cs
As the runtime returns a 200 even if there's no reminder registered, I've added more logic to determine if any deserialization happens successfully on the payload and returns null if not, preventing the return of a `ReminderInfo` that contains all default values.
Another PR aiming to conclusively fix #1468 
Please reference the issue this PR will close: #1468
* [N/A] Extended the documentation
=> Fix: Actor reminders should return null if not registered

test/Dapr.Actors.Test/Runtime/DefaultActorTimerManagerTests.cs
While investigating #1464 , I discovered that there already existed several unit tests with one on point. While I'm unable to recreate the issue detailed, I did notice that there were a few improvements to make to the unit tests in this class, including:
- The `GetReminderAsync_ReturnsResultWhenAvailable` test double checked the `Period` property instead of checking both `Period` and `DueTime`.
- Several actor callbacks re-used the same variable names as outside the delegate.
- Used `const string` where possible instead of `var`.
- Removed unused usings
- Removed unused variables in tests
- Added Dapr copyright header
Please reference the issue this PR will …
=> Fixed unit tests validating actor reminder deserialization

src/Dapr.AI/Conversation/DaprConversationClient.cs
A developer can pass options into the Conversations API that change the behavior. When options are passed today without a `ConversationId` value, this throws as it expects that to be populated.
This patch fixes this - `ConversationId` is optional and will be treated as such.
Thanks for spotting this issue @marcduiker !
N/A
=> Fixed `ConversationOptions` not accepting unset `ConversationId`

daprdocs/content/en/dotnet-sdk-contributing/dotnet-contributing.md, daprdocs/content/en/dotnet-sdk-docs/_index.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-howto.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-ai/dotnet-ai-conversation-howto.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-development/dotnet-development-dapr-aspire.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-jobs/dotnet-jobs-howto.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-messaging/dotnet-messaging-pubsub-howto.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-workflow/dotnet-workflow-howto.md, examples/Actor/README.md, examples/AspNetCore/ControllerSample/README.md, examples/AspNetCore/GrpcServiceSample/README.md, examples/AspNetCore/RoutingSample/README.md, examples/AspNetCore/SecretStoreConfigurationProviderSample/README.md, examples/Client/ConfigurationApi/README.md, examples/Client/DistributedLock/README.md, examples/Client/PublishSubscribe/BulkPublishEventExample/README.md, examples/Client/PublishSubscribe/PublishEventExample/README.md, examples/Client/ServiceInvocation/README.md, examples/Client/StateManagement/README.md, examples/GeneratedActor/README.md, examples/Workflow/README.md, properties/dapr_managed_netcore.props
Updated all the documentation to reflect support for .NET 8 and 9 throughout, updated examples and READMEs accordingly.
Also increased the minimum C# langversion from 10.0 to 12.0 as C# 12 was released with .NET 8.
Please reference the issue this PR will close: #1429 
=> Additional commits to drop .NET 6 and 7

src/Dapr.Actors/Runtime/ActorManager.cs, src/Dapr.Actors/Runtime/ConverterUtils.cs, test/Dapr.Actors.Test/Runtime/ActorManagerTests.cs
Implements https://github.com/dapr/dotnet-sdk/pull/1483 but for actor timers. Still needs unit testing before release.
Please reference the issue this PR will close: #1511 
=> Tentative fix for timers deserializing error

Directory.Packages.props
Attempting to fix scheduler reconnection issue being experienced by clients using .NET 9.
=> Updating gRPC and Microsoft.DurableTask.* packages

src/Dapr.Workflow/WorkflowLoggingService.cs
This should help with issue #1273 - intermittent exceptions from WorkflowLoggingService.
There is no concurrent HashSet in .NET, so we use ConcurrentDictionary with a byte as the value to simulate a set. For this use-case we do not care if the Key already exists, so we can use TryAdd to add items without considering the return value.
Replaces `HashSet<string>` as the collection that stores Activity and Workflow names for logging with `ConcurrentDictionary<string, byte>`
Please reference the issue this PR will close: #1273
=> Replace HashSet with ConcurrentDictionary in WorkflowLoggingService

.github/workflows/publish.yml, .github/workflows/sdk_build.yml
Updating GitHub workflow to split out publishing to a separate workflow that's dependent on the success of both the sdk_build.yml and itests.yml completing. Publish isn't firing because of a misconfiguration in the workflow today.
=> Updating publish script workflow

all.sln, src/Dapr.AI.A2A/Dapr.AI.A2A.csproj, src/Dapr.AI.A2A/DaprTaskStore.cs
Added project to larger solution, fixed missing assignment in constructor, several optimizations for modern C# syntax, removed some unreachable code.
=> Tweaks to A2A project

daprdocs/content/en/dotnet-sdk-docs/dotnet-messaging/_index.md
Link was using a static URL instead of the relative documentation format we generally expect in the documentation (e.g. to allow version shifts).
=> Fixed incorrect link format

daprdocs/content/en/dotnet-sdk-docs/dotnet-ai/dotnet-ai-conversation-howto.md, daprdocs/content/en/dotnet-sdk-docs/dotnet-ai/dotnet-ai-extensions-howto.md
Some of the weights for AI docs included an extra zero putting them out of range to display. This should fix this.
=> Fixed weights to make two missing AI docs show up
